import type { Strings } from '../../i18n';
export const strings:Strings={
  en:{'tools.board':'Sign-out board','tools.all':'All tools','tools.inShop':'In the shop','tools.with':'With {name}{project} · since {time}','tools.at':' · {project}','tools.take':'Take','tools.return':'Return','tools.returnTake':'Return and take','tools.broken':'Broken: {body}','tools.reportBroken':'Report broken','tools.resolve':'Mark repaired','tools.needsSignOut':'Needs sign-out','tools.noSignOut':'No sign-out','tools.noneBoard':'No tools need sign-out yet. A manager or owner turns it on under All tools.','tools.noneAll':'No equipment yet. Add it under Inventory.','tools.history':'History','tools.taken':'Taken by {name} · {time}','tools.returned':'Returned by {name} · {time}','tools.cleanedBy':'Cleaned by {name} · {time}','tools.reportedBy':'Reported by {name} · {time}','tools.resolvedBy':'Repaired · {name}',
    'tools.dialog.title':'Tool sign-out','tools.dialog.tool':'Tool','tools.dialog.project':'Project used (optional)','tools.dialog.noProject':'No project','tools.dialog.note':'Note (optional)','tools.dialog.take':'Take it','tools.dialog.taken':'Tool signed out.','tools.dialog.returned':'Tool returned.','tools.dialog.noneAvailable':'Every sign-out tool is already out.','tools.report.title':'Report broken','tools.report.body':'What is wrong?','tools.report.save':'Send report','tools.report.saved':'Report sent.','tools.returnConfirm':'Return {name}?',
    'inventory.materialsMoved':'The shopping list became Materials requests.','inventory.openMaterials':'Open Materials requests','shell.install.title':'Install this app','shell.install.hint':'Add it to your home screen to open it like an app.','shell.install.button':'Install','shell.install.ios':'On iPhone: Share → Add to Home Screen.'},
  es:{'tools.board':'Tablero de préstamos','tools.all':'Todas las herramientas','tools.inShop':'En el taller','tools.with':'Con {name}{project} · desde {time}','tools.at':' · {project}','tools.take':'Tomar','tools.return':'Devolver','tools.returnTake':'Devolver y tomar','tools.broken':'Dañada: {body}','tools.reportBroken':'Reportar daño','tools.resolve':'Marcar reparada','tools.needsSignOut':'Requiere préstamo','tools.noSignOut':'Sin préstamo','tools.noneBoard':'Ninguna herramienta requiere préstamo aún. Un manager o dueño lo activa en Todas las herramientas.','tools.noneAll':'Aún no hay equipo. Agrégalo en Inventario.','tools.history':'Historial','tools.taken':'Tomada por {name} · {time}','tools.returned':'Devuelta por {name} · {time}','tools.cleanedBy':'Limpiada por {name} · {time}','tools.reportedBy':'Reportada por {name} · {time}','tools.resolvedBy':'Reparada · {name}',
    'tools.dialog.title':'Préstamo de herramienta','tools.dialog.tool':'Herramienta','tools.dialog.project':'Proyecto donde se usa (opcional)','tools.dialog.noProject':'Sin proyecto','tools.dialog.note':'Nota (opcional)','tools.dialog.take':'Tomarla','tools.dialog.taken':'Herramienta prestada.','tools.dialog.returned':'Herramienta devuelta.','tools.dialog.noneAvailable':'Todas las herramientas de préstamo ya están fuera.','tools.report.title':'Reportar daño','tools.report.body':'¿Qué tiene?','tools.report.save':'Enviar reporte','tools.report.saved':'Reporte enviado.','tools.returnConfirm':'¿Devolver {name}?',
    'inventory.materialsMoved':'La lista de compras ahora es Pedidos de material.','inventory.openMaterials':'Abrir Pedidos de material','shell.install.title':'Instalar esta app','shell.install.hint':'Agrégala a tu pantalla de inicio para abrirla como una app.','shell.install.button':'Instalar','shell.install.ios':'En iPhone: Compartir → Agregar a pantalla de inicio.'},
};
