import { useEffect, useRef, useState } from 'react';
import { appStateSchema } from '@pirata/domain/domain/schema';
import type { AppState } from '@pirata/domain/domain/types';
import type { ImportPreview, ImportRequest } from '@pirata/contracts/import';
import { useServer } from '../state/serverContext';
import { localStorageRepository } from '../data/localStorageRepository';
import { ServiceError } from '../services/api';
function downloadText(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function DataTools(){
 const {store}=useServer(),[raw,setRaw]=useState(''),[source,setSource]=useState<AppState|null>(null),[preview,setPreview]=useState<ImportPreview|null>(null),[choice,setChoice]=useState<''|'carry'|'discard'>(''),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState(''),[phase,setPhase]=useState<'editing'|'busy'|'uncertain'|'saved'>('editing');
 const submission=useRef<ImportRequest|null>(null),busy=useRef(false),acknowledged=useRef(false),readGeneration=useRef(0);
 const frozen=phase!=='editing';
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(submission.current||busy.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[]);
 function read(text:string){if(busy.current||submission.current)return;setRaw(text);setPreview(null);setConfirmed(false);submission.current=null;setChoice('');const parsed=appStateSchema.safeParse((()=>{try{return JSON.parse(text);}catch{return null;}})());if(!parsed.success){setSource(null);setMessage('This is not a valid v1 demo export. Nothing was changed. '+parsed.error.issues.map(i=>[i.path.join('.'),i.message].filter(Boolean).join(': ')).slice(0,8).join('; '));return;}setSource(parsed.data);setMessage('File validated. Review the sample records and choose how to handle an active timer before previewing.');}
 function readBrowser(){readGeneration.current++;try{const value=localStorageRepository().read();if(value===null){setMessage('No local demo records exist at this browser origin. Export them from the original browser and select that file here.');return;}read(value);}catch{setMessage('Browser storage is unavailable. Select a previously exported file instead.');}}
 async function showPreview(){if(!source||busy.current)return;if(source.runningTimer&&!choice){setMessage('Choose carry or discard for the active timer.');document.getElementById('import-timer-choice')?.focus();return;}busy.current=true;setPhase('busy');try{setPreview(await store.service.previewImport({state:source,timerChoice:choice||'discard'}));setMessage('Preview only. No business records have been saved.');}catch(e){setPreview(null);setMessage(e instanceof Error?e.message:'Could not preview.');}finally{busy.current=false;setPhase('editing');}}
 async function commit(){if(busy.current)return;if(!submission.current){if(!source||!preview||!confirmed)return;submission.current={requestId:crypto.randomUUID(),baseRevision:preview.baseRevision,confirmed:true,state:source,timerChoice:choice||'discard'};}busy.current=true;setPhase('busy');try{const session=await store.service.session();if(!session.authenticated)throw new ServiceError(401,{code:'UNAUTHENTICATED',message:'Sign in again in another tab, then retry this same import.'});if(!acknowledged.current){await store.service.importData(submission.current);acknowledged.current=true;}await store.refresh();setSource(null);setPreview(null);setRaw('');submission.current=null;acknowledged.current=false;setPhase('editing');setMessage('Import completed. The original browser demo and source file are unchanged.');}catch(e){if(acknowledged.current){setPhase('saved');setMessage('Imported on the server. Refresh failed; retry to reload, without importing again.');}else if(e instanceof ServiceError&&[400,409,413,422].includes(e.status)){submission.current=null;setPreview(null);setConfirmed(false);setPhase('editing');setMessage(e.message+' Preview again after reviewing.');}else{setPhase('uncertain');setMessage(e instanceof Error?e.message:'Import response unconfirmed. Retry the same import.');}}finally{busy.current=false;}}
 return <section data-import-phase={phase} className="card data-tools" aria-label="Data and recovery"><h2>Data & recovery</h2><p>Live records are stored in your private server workspace. Download a business export for your own records. Restoring a database backup is a separate administrator operation.</p><button onClick={()=>void store.service.exportData().then(data=>{downloadText('pirata-business-v2.json',JSON.stringify(data,null,2));setMessage('Business export downloaded. It contains no sign-in credentials.');}).catch(e=>setMessage(e instanceof Error?e.message:'Export failed.'))}>Download business export</button>
 <h3>Bring over a browser demo</h3><p>Import is allowed only into an empty live workspace. Sample records are fabricated; review them before importing. This never replaces your original browser data.</p>
 <fieldset disabled={frozen}><div className="live-actions"><button onClick={readBrowser}>Read this browser's demo</button><button onClick={()=>{try{const value=localStorageRepository().read();if(value===null){setMessage('No demo data in this browser.');return;}downloadText('pirata-original-browser-demo.json',value);}catch{setMessage('Browser storage unavailable.');}}}>Download original browser demo</button></div><label htmlFor="demo-file">Choose v1 demo JSON file</label><input id="demo-file" type="file" accept="application/json,.json" onChange={e=>{const file=e.target.files?.[0];if(file){if(file.size>2*1024*1024){setMessage('File is too large. Maximum 2 MiB.');return;}const token=++readGeneration.current;void file.text().then(text=>{if(token===readGeneration.current)read(text);}).catch(()=>setMessage('Could not read this file. Nothing was changed.'));}}}/>
 {raw&&!source&&<button onClick={()=>downloadText('pirata-unmodified-recovery.json',raw)}>Download unmodified content for recovery</button>}
 {source&&<><p>Original sample date: {source.seededOn}.</p><ul><li>{source.projects.length} projects: {source.projects.slice(0,3).map(p=>p.name).join(', ')||'None'}</li><li>{source.tasks.length} tasks: {source.tasks.slice(0,3).map(t=>t.title).join(', ')||'None'}</li><li>{source.expenses.length} purchases; {source.materials.length} materials; {source.leads.length} leads.</li></ul>{source.runningTimer&&<><label htmlFor="import-timer-choice">Active timer decision</label><select id="import-timer-choice" value={choice} onChange={e=>{setChoice(e.target.value as typeof choice);setPreview(null);setConfirmed(false);}}><option value="">Choose explicitly</option><option value="carry">Carry the original running session</option><option value="discard">Discard the active session; keep completed history</option></select><p>Carrying it keeps counting from {new Date(source.runningTimer.startedAt).toISOString()}, including time while the browser was closed. Discarding creates no time entry.</p></>}<button onClick={()=>void showPreview()}>Preview import</button></>}
 {preview&&<><h3>Import preview</h3><dl className="counts">{Object.entries(preview.counts).map(([name,count])=><div key={name}><dt>{name}</dt><dd>{count}</dd></div>)}</dl><ul>{preview.warnings.map(w=><li key={w}>{w}</li>)}</ul><p>{preview.activeTimer?'One timer will remain running.':'No active timer will be imported.'}</p><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the sample records and confirm importing them into this empty workspace.</label><button className="primary" disabled={!confirmed} onClick={()=>void commit()}>Confirm import</button></>}
 </fieldset>{(phase==='uncertain'||phase==='saved')&&<button className="primary" onClick={()=>void commit()}>{phase==='saved'?'Reload imported records':'Retry same import'}</button>}{message&&<p role="status" className="info-panel">{message}</p>}{phase==='busy'&&<p role="status">Working…</p>}<p>There is no live “reset everything” button. The separate sample demo can be reset from its Demo dialog.</p></section>;
}
