import { Suspense, useState, useRef } from 'react';
import type { LucideIcon } from 'lucide-react';
import { can } from '@pirata/contracts/permissions';
import { dialogRegistry, type RegisteredDialogName } from './dialogRegistry';
import { tx, useT } from '../i18n';
import { taskDepth } from '@pirata/contracts/index';
import { canEditDone } from '../features/work/dayList';
import { TaskExtras } from '../features/tasks-time/TaskExtras';
import { DeleteButton, mayDelete } from '../features/trash';
import { TranslatedText } from '../components/TranslatedText';
const pad=(n:number)=>String(n).padStart(2,'0');
/** Device-local calendar date and clock time for a timestamp; the phone and the business share America/New_York. */
export const localDate=(ms:number)=>{const d=new Date(ms);return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());};
export const localTime=(ms:number)=>{const d=new Date(ms);return pad(d.getHours())+':'+pad(d.getMinutes());};
export const localTimestamp=(date:string,time:string)=>{const [y,m,d]=date.split('-').map(Number),[h,min]=time.split(':').map(Number);return new Date(y,m-1,d,h||0,min||0).getTime();};
import { CalendarDays, Check, ChevronRight, CircleDollarSign, ClipboardList, Clock3, Folder, MessageSquare, PackagePlus, Pause, Pencil, Play, Plus, UserPlus, Wrench } from 'lucide-react';
import type { BusinessCommand, TimeEntry } from '@pirata/contracts/index';
import { toLegacyState } from '@pirata/contracts/compatibility';
import { actualTaskTime, estimateVariance } from '@pirata/domain/domain/selectors';
import { entryMilliseconds, formatClock, formatDuration } from '@pirata/domain/lib/time';
import { parseQuantity } from '@pirata/domain/lib/money';
import type { ModuleProps } from '../services/moduleProps';
import { WorkDialog } from '../features/tasks-time/WorkDialog';
import { WorkForm } from '../features/tasks-time/WorkForm';
import { FilesPanel } from '../features/collaboration';
import { TaskEditor, TaskChecklist } from '../features/tasks-time';
import { ScheduleTaskDialog } from '../features/planning';
import { ExpenseForm } from '../features/spending';
import { MaterialDetail, MaintenanceDetail } from '../features/inventory';
import { FollowUpForm } from '../features/clients-projects/forms';
export type Dialog = {kind:'quick'|'task-new'|'expense'|'task'|'task-edit'|'plan'|'time'|'time-edit'|'manual'|'material'|'maintenance'|'adjustment'|'lead'|'follow-up'|'objectives'|'registry';id?:string;projectId?:string;parentTaskId?:string;fromQuick?:boolean;focusChoice?:string;name?:RegisteredDialogName;date?:string;prefill?:{title?:string;quantity?:string}}|{kind:'action';title:string;command:BusinessCommand;description:string};
type Props={app:ModuleProps;dialog:Dialog;open(d:Dialog|null,confirmedClose?:boolean):void;now:number};
export function LiveDialogs({app,dialog:d,open,now}:Props){
 const leadName=useRef(''),t=useT();
 // Cancel goes up one Add level; a confirmed save still returns to the workspace.
 const fromQuick='fromQuick' in d&&d.fromQuick, backLabel=fromQuick?tx('Back to Add menu'):undefined;
 const done=()=>open(null),close=()=>open(fromQuick?{kind:'quick',focusChoice:d.kind,projectId:d.projectId,parentTaskId:d.parentTaskId}:null,true),task=app.snapshot.tasks.find(t=>'id' in d&&t.id===d.id),selection='id' in d?d.id:undefined;
 if(d.kind==='task-new'||d.kind==='task-edit'){
  const returnToSubtask=d.kind==='task-edit'&&task?.parentTaskId?()=>open({kind:'task',id:task.id},true):undefined;
  return <TaskEditor {...app} selection={{taskId:d.kind==='task-edit'?d.id:undefined,projectId:d.projectId}} onClose={returnToSubtask??close} parentTaskId={d.parentTaskId} backLabel={returnToSubtask?tx('Back to subtask'):backLabel} onDone={returnToSubtask??done}/>;
 }
 if(d.kind==='expense')return <ExpenseForm {...app} selection={{expenseId:d.id,projectId:d.projectId}} onClose={close} backLabel={backLabel} onDone={done}/>;
 if(d.kind==='plan')return <ScheduleTaskDialog {...app} selection={{taskId:d.id}} onClose={close}/>;
 if(d.kind==='material')return <MaterialDetail {...app} selection={{materialId:d.id}} onClose={close}/>;
 if(d.kind==='maintenance')return <MaintenanceDetail {...app} selection={{maintenanceId:d.id}} onClose={close}/>;
 if(d.kind==='action')return <WorkDialog title={d.title} onClose={close}><WorkForm app={app} initial={{startedDate:localDate(app.snapshot.runningTimer?.startedAt??now),startedTime:localTime(app.snapshot.runningTimer?.startedAt??now)}} command={v=>d.command.type==='timer.correctStart'?{...d.command,startedAt:localTimestamp(v.startedDate,v.startedTime)}:d.command} message={d.title+' '+tx('saved.')} done={done} submitLabel={tx('Confirm')+' '+d.title.toLowerCase()}>{draft=><><p>{d.description}</p>{d.command.type==='timer.correctStart'&&<>{draft.field('startedDate',t('tasks.startDate'),{type:'date'})}{draft.field('startedTime',t('tasks.startTime'),{type:'time',hint:t('tasks.timeHint')})}</>}</>}</WorkForm></WorkDialog>;
 if(d.kind==='registry'&&d.name){const Registered=dialogRegistry[d.name];return <Suspense fallback={null}><Registered app={app} projectId={d.projectId} taskId={d.id} date={d.date} prefill={d.prefill} onClose={close} onDone={done}/></Suspense>;}
 if(d.kind==='quick'){
  // Explicit Add menu (update 2026-09-25): one tap per record type, no 'Back to Add menu' step. Chunk dialogs come from dialogRegistry.
  const role=app.snapshot.currentUser?.role;
  const entries:[Dialog,string,LucideIcon][]=[[{kind:'task-new',projectId:d.projectId,parentTaskId:d.parentTaskId},'task',ClipboardList],[{kind:'registry',name:'project-new'},'project',Folder],[{kind:'registry',name:'material-request',projectId:d.projectId},'materialRequest',PackagePlus],[{kind:'registry',name:'shift',projectId:d.projectId},'shift',Clock3],[{kind:'registry',name:'tool-signout',projectId:d.projectId},'toolSignOut',Wrench],[{kind:'registry',name:'question',projectId:d.projectId},'question',MessageSquare],...(can(role,'money.costs')?[[{kind:'expense',projectId:d.projectId},'expense',CircleDollarSign] as [Dialog,string,LucideIcon]]:[]),[{kind:'lead'},'lead',UserPlus]];
  return <WorkDialog title={t('shell.add.title')} onClose={close} initialFocusSelector={d.focusChoice?'[data-quick-kind="'+d.focusChoice+'"]':undefined}><div className="quick-choices">{entries.map(([target,label,Icon])=><button key={label} data-quick-kind={label} onClick={()=>open(target)}><Icon size={22} aria-hidden="true"/><span><strong>{t('shell.add.'+label)}</strong><small>{t('shell.add.'+label+'.desc')}</small></span><ChevronRight size={17} aria-hidden="true"/></button>)}</div></WorkDialog>;
 }
 if(d.kind==='objectives')return <ObjectivesForm app={app} close={close}/>;
 if(d.kind==='task'){
  if(!task)return <WorkDialog title={tx('Task unavailable')} onClose={close}><p>{tx('Refresh to load the latest records.')}</p></WorkDialog>;
  const state=toLegacyState(app.snapshot),total=actualTaskTime(state,task.id,now),timer=app.snapshot.runningTimer;
  const status=(status:'open'|'blocked'|'done')=>open({kind:'action',title:status==='open'?tx('Reopen task'):status==='done'?tx('Finish task'):tx('Block task'),command:{type:'task.setStatus',id:task.id,status,expectedSessionId:status!=='open'&&timer&&(timer.taskId===task.id||status==='done'&&app.snapshot.tasks.some(t=>t.id===timer.taskId&&t.parentTaskId===task.id))?timer.sessionId:null},description:status==='open'?tx('Reopen this task and retain its time history?'):status==='done'?tx('Complete this task and its remaining subtasks, and save your active work interval if applicable?'):tx('Mark this task as blocked and save your active work interval, if applicable?') });
  const isRunning=timer?.taskId===task.id;
  const timerTitle=isRunning?tx('Pause timer'):timer?tx('Switch timer'):tx('Start timer');
  const timerCommand:BusinessCommand=isRunning?{type:'timer.pause',expectedSessionId:timer.sessionId}:timer?{type:'timer.switch',taskId:task.id,expectedSessionId:timer.sessionId}:{type:'timer.start',taskId:task.id};
  const parent=app.snapshot.tasks.find(item=>item.id===task.parentTaskId),depth=taskDepth(app.snapshot.tasks,task.id),editable=canEditDone(task,app.snapshot.currentUser?.id,app.snapshot.currentUser?.role,now),isOwner=app.snapshot.currentUser?.role==='owner';
  return <WorkDialog title={parent?tx('Subtask details'):tx('Task details')} className="task-detail-dialog" onClose={parent?()=>open({kind:'task',id:parent.id},true):close} backLabel={parent?tx('Back to parent task'):undefined}>
    {parent&&<p className="task-parent-hint">{tx('Subtask of')} <TranslatedText kind="task" id={parent.id} field="title" text={parent.title} compact/>{!task.assignmentExplicit?' · '+tx('assignment inherited'):''}</p>}
    <div className="task-detail-intro"><h3><TranslatedText kind="task" id={task.id} field="title" text={task.title}/></h3>{task.description&&<TranslatedText kind="task" id={task.id} field="description" text={task.description} as="p" className="task-detail-description"/>}<p className="task-detail-context">{app.snapshot.projects.find(p=>p.id===task.projectId)?.name??tx('Unfiled')} · {task.assigneeId?tx('Assigned to')+' '+(app.snapshot.team?.find(person=>person.id===task.assigneeId)?.name??tx('team member')):tx('Unassigned')}</p>{task.status!=='open'&&<span className={'badge badge-'+task.status}>{task.status==='done'?tx('Complete'):tx('Blocked')}</span>}{task.note&&<TranslatedText kind="task" id={task.id} field="note" text={task.note} as="p" className="task-detail-note"/>}</div>
    {depth<2&&<TaskChecklist {...app} parentTaskId={task.id}/>}
    <TaskExtras app={app} task={task}/>
    <section className="task-detail-timer" aria-label={tx('Task time tracking')}><h3>{tx('Time tracking')}</h3><div className="task-detail-time-row"><strong>{isRunning&&now<timer.startedAt?tx('Clock correction needed'):formatClock(isRunning?now-timer.startedAt:total)}</strong>{task.status==='open'&&<button className="task-primary" disabled={Boolean(isRunning&&now<timer.startedAt)} onClick={()=>open({kind:'action',title:timerTitle,command:timerCommand,description:isRunning?tx('Save this work interval and pause the timer?'):timer?tx('Save your current interval and start work on {title}?',{title:task.title}):tx('Start work on {title}? Your timer continues until you pause or finish.',{title:task.title})})}>{isRunning?<Pause size={17} aria-hidden="true"/>:<Play size={17} aria-hidden="true"/>}{timerTitle}</button>}</div><p>{formatDuration(total)} {tx('logged')}{task.estimatedMinutes>0?' · '+formatDuration(task.estimatedMinutes*60000)+' '+tx('estimated'):''}</p>{estimateVariance(task,total)&&<p>{estimateVariance(task,total)}</p>}</section>
    <div className="task-detail-primary">{task.status==='open'?<button onClick={()=>status('done')}><Check size={17} aria-hidden="true"/>{tx('Finish task')}</button>:editable?<button onClick={()=>status('open')}>{task.status==='done'&&!isOwner?t('tasks.undo'):t('tasks.reopen')}</button>:<p className="muted">{t('tasks.locked')}</p>}</div>
    <div className="task-detail-tools">{!parent&&editable&&<button onClick={()=>open({kind:'task-edit',id:task.id})}><Pencil size={16} aria-hidden="true"/>{tx('Edit task')}</button>}<button onClick={()=>open({kind:'plan',id:task.id})}><CalendarDays size={16} aria-hidden="true"/>{tx('Schedule / reschedule')}</button><button onClick={()=>open({kind:'time',id:task.id})}><Clock3 size={16} aria-hidden="true"/>{tx('Time entries')}</button>{depth<2&&<button onClick={()=>open({kind:'task-new',parentTaskId:task.id,projectId:task.projectId??undefined})}><Plus size={16} aria-hidden="true"/>{depth===0?t('tasks.addSubtask'):t('tasks.addTiny')}</button>}</div>
    <FilesPanel app={app} parentType="task" parentId={task.id}/>
    {(task.status==='open'||mayDelete(app,'task',task as unknown as Record<string,unknown>))&&<details className="task-secondary-actions"><summary>{tx('More task actions')}</summary>{task.status==='open'&&<button onClick={()=>status('blocked')}>{tx('Block task')}</button>}{mayDelete(app,'task',task as unknown as Record<string,unknown>)&&<DeleteButton app={app} kind="task" id={task.id} label={task.title} onDone={close}/>}</details>}
    {parent&&editable&&<footer className="work-actions task-subtask-edit"><button className="work-primary" onClick={()=>open({kind:'task-edit',id:task.id})}><Pencil size={16} aria-hidden="true"/>{tx('Edit subtask')}</button></footer>}
  </WorkDialog>;
 }
 if(d.kind==='time')return <WorkDialog title={tx('Time entries')} onClose={close}><p>{task?.title??tx('All tasks')}. {tx('Correct a recorded entry explicitly; the original session is never counted twice.')}</p><button onClick={()=>open({kind:'manual',id:d.id})}>{tx('Add manual time')}</button><ul className="live-records">{app.snapshot.timeEntries.filter(e=>!d.id||e.taskId===d.id).map(e=><li key={e.id}><strong>{formatDuration(entryMilliseconds(e))}</strong><p>{e.source==='manual'?e.date+' · '+tx('Manual'):new Date(e.startedAt).toISOString()+' → '+new Date(e.endedAt).toISOString()}</p><p>{e.note}</p><button onClick={()=>open({kind:'time-edit',id:e.id})}>{tx('Correct entry')}</button></li>)}</ul></WorkDialog>;
 if(d.kind==='manual'||d.kind==='time-edit')return <TimeForm app={app} entry={d.kind==='time-edit'?app.snapshot.timeEntries.find(e=>e.id===d.id):undefined} taskId={d.kind==='manual'?d.id:undefined} close={close} done={done} backLabel={backLabel}/>;
 if(d.kind==='adjustment')return <WorkDialog title={tx('Material adjustment')} onClose={close} backLabel={backLabel}><WorkForm app={app} initial={{materialId:d.id??app.snapshot.materials[0]?.id??'',deltaMinor:'',reason:'restock',note:''}} command={v=>({type:'material.adjust',materialId:v.materialId,deltaMinor:parseQuantity(v.deltaMinor)??NaN,reason:v.reason as 'restock'|'usage'|'correction',note:v.note})} validate={(v):Record<string,string>=>{const m=app.snapshot.materials.find(m=>m.id===v.materialId),q=parseQuantity(v.deltaMinor);return q===null||q===0?{deltaMinor:'Enter a nonzero signed quantity with at most two decimals.'}:m?.unit==='piece'&&q%100!==0?{deltaMinor:'Pieces require whole units.'}:{};}} message={tx('Material stock updated. Spending is unchanged.')} done={done}>{f=><><p>{tx('Quantity changes do not record purchases. Add an expense separately.')}</p>{f.field('materialId',tx('Material'),{options:app.snapshot.materials.map(m=>({value:m.id,label:m.name+' ('+m.unit+')'}))})}{f.field('deltaMinor',tx('Signed quantity adjustment'),{hint:tx('Use a minus sign for usage. Stock cannot fall below reservations.')})}{f.field('reason',tx('Reason'),{options:['restock','usage','correction'].map(value=>({value,label:value}))})}{f.field('note',tx('Note (optional)'),{type:'textarea'})}{!app.snapshot.materials.length&&<p>{tx('Add a material in Inventory first.')}</p>}</>}</WorkForm></WorkDialog>;
 if(d.kind==='lead')return <WorkDialog title={tx('Add lead')} onClose={close} backLabel={backLabel}><WorkForm app={{...app,onSaved:()=>app.onSaved(tx('Lead saved:')+' '+leadName.current)}} initial={{name:'',phone:'',email:'',workDescription:'',nextFollowUpDate:''}} command={v=>{leadName.current=v.name.trim();return {type:'lead.create',name:v.name,phone:v.phone,email:v.email.trim(),workDescription:v.workDescription,nextFollowUpDate:v.nextFollowUpDate||null};}} message={tx('Lead saved.')} done={done}>{f=><>{f.field('name',tx('Name'))}{f.field('phone',tx('Phone (optional)'),{type:'tel'})}{f.field('email',tx('Email (optional)'),{type:'email'})}{f.field('workDescription',tx('Work description'))}{f.field('nextFollowUpDate',tx('Follow-up date (optional)'),{type:'date'})}<p>{tx('The lead stays in Clients → Leads, including when no reminder is due.')}</p></>}</WorkForm></WorkDialog>;
 if(d.kind==='follow-up'){const lead=app.snapshot.leads.find(l=>l.id===selection);return <WorkDialog title={tx('Client follow-up')} onClose={close}>{lead?<><h3>{lead.name}</h3><p>{lead.workDescription}</p><p>{lead.phone||tx('No phone')} · {lead.email||tx('No email')}</p><FollowUpForm app={app} lead={lead} done={done}/></>:<p>{tx('Lead unavailable.')}</p>}</WorkDialog>;}
 return null;
}
function TimeForm({app,entry,taskId,close,done,backLabel}:{app:ModuleProps;entry?:TimeEntry;taskId?:string;close():void;done():void;backLabel?:string}){return <WorkDialog title={entry?tx('Correct time entry'):tx('Add time entry')} onClose={close} backLabel={backLabel}><WorkForm app={app} initial={{taskId:entry?.taskId??taskId??app.snapshot.tasks[0]?.id??'',date:entry?.source==='manual'?entry.date:app.businessDate,minutes:String(entry?.source==='manual'?entry.durationSeconds/60:30),note:entry?.note??'',startedDate:entry?.source==='timer'?localDate(entry.startedAt):'',startedTime:entry?.source==='timer'?localTime(entry.startedAt):'',endedDate:entry?.source==='timer'?localDate(entry.endedAt):'',endedTime:entry?.source==='timer'?localTime(entry.endedAt):''}} command={v=>entry?{type:'timeEntry.correct',id:entry.id,correction:entry.source==='timer'?{source:'timer',startedAt:localTimestamp(v.startedDate,v.startedTime),endedAt:localTimestamp(v.endedDate,v.endedTime),note:v.note}:{source:'manual',date:v.date,minutes:Number(v.minutes),note:v.note}}:{type:'timeEntry.createManual',taskId:v.taskId,date:v.date,minutes:Number(v.minutes),note:v.note}} message={entry?tx('Time entry corrected.'):tx('Time entry added.')} done={done}>{f=><>{!entry&&f.field('taskId',tx('Task'),{options:app.snapshot.tasks.map(t=>({value:t.id,label:t.title}))})}{entry?.source==='timer'?<>{f.field('startedDate',tx('Start date'),{type:'date'})}{f.field('startedTime',tx('Start time'),{type:'time'})}{f.field('endedDate',tx('End date'),{type:'date'})}{f.field('endedTime',tx('End time'),{type:'time'})}</>:<>{f.field('date',tx('Work date'),{type:'date'})}{f.field('minutes',tx('Duration in whole minutes'),{type:'number'})}</>}{f.field('note',tx('Note (optional)'),{type:'textarea'})}</>}</WorkForm></WorkDialog>;}
function ObjectivesForm({app,close}:{app:ModuleProps;close():void}){
 const [editingDate]=useState(app.businessDate);
 const objectives=app.snapshot.objectives.filter(o=>o.date===editingDate).sort((a,b)=>a.rank-b.rank),initial:Record<string,string>={count:String(objectives.length)};
 const keys=['id','title','taskId','status','note'] as const;objectives.forEach((o,i)=>keys.forEach(k=>{initial[`objectives.${i}.${k}`]=o[k]??'';}));
 return <WorkDialog title={tx('Edit objectives')} onClose={close}><WorkForm app={app} initial={initial} command={v=>({type:'objectives.replaceForDate',date:editingDate,objectives:Array.from({length:Number(v.count)},(_,i)=>({id:v[`objectives.${i}.id`],title:v[`objectives.${i}.title`],taskId:v[`objectives.${i}.taskId`]||null,status:v[`objectives.${i}.status`] as 'open'|'partial'|'blocked'|'done',note:v[`objectives.${i}.note`],rank:i}))})} message={tx("Today's objectives saved.")} done={close}>{f=><><p>Up to three outcomes for {editingDate}. Task completion is separate.</p>{Array.from({length:Number(f.values.count)},(_,i)=><fieldset key={f.values[`objectives.${i}.id`]} className="objective-editor"><legend>Objective {i+1}</legend>{f.field(`objectives.${i}.title`,`Objective ${i+1} title`)}{f.field(`objectives.${i}.taskId`,`Objective ${i+1} task`,{options:[{value:'',label:tx('No linked task')},...app.snapshot.tasks.map(t=>({value:t.id,label:t.title}))]})}{f.field(`objectives.${i}.status`,`Objective ${i+1} status`,{options:['open','partial','blocked','done'].map(value=>({value,label:value}))})}{f.field(`objectives.${i}.note`,`Objective ${i+1} note`,{type:'textarea',hint:tx('Explain the reason when blocked.')})}<div className="live-actions">{[-1,1].map(delta=><button key={delta} type="button" data-dirty disabled={i+delta<0||i+delta>=Number(f.values.count)} onClick={()=>{const v={...f.values};for(const k of keys){v[`objectives.${i}.${k}`]=f.values[`objectives.${i+delta}.${k}`];v[`objectives.${i+delta}.${k}`]=f.values[`objectives.${i}.${k}`];}f.replace(v);}}>{delta<0?'Up':'Down'}</button>)}<button type="button" data-dirty onClick={()=>{const v:Record<string,string>={...f.values,count:String(Number(f.values.count)-1)};for(let n=i;n<Number(v.count);n++)for(const k of keys)v[`objectives.${n}.${k}`]=f.values[`objectives.${n+1}.${k}`];f.replace(v);}}>{tx('Remove')}</button></div></fieldset>)}<button type="button" data-dirty disabled={Number(f.values.count)>=3} onClick={()=>{const i=Number(f.values.count);f.replace({...f.values,count:String(i+1),[`objectives.${i}.id`]:crypto.randomUUID(),[`objectives.${i}.title`]:'',[`objectives.${i}.taskId`]:'',[`objectives.${i}.status`]:'open',[`objectives.${i}.note`]:''});}}>{tx('Add objective')}</button></>}</WorkForm></WorkDialog>;
}
