import { useState, useRef } from 'react';
import { CalendarDays, Check, ChevronRight, CircleDollarSign, ClipboardList, Clock3, PackagePlus, Pause, Pencil, Play, Plus, UserPlus } from 'lucide-react';
import type { BusinessCommand, TimeEntry } from '@pirata/contracts/index';
import { toLegacyState } from '@pirata/contracts/compatibility';
import { actualTaskTime, estimateVariance } from '@pirata/domain/domain/selectors';
import { entryMilliseconds, formatClock, formatDuration } from '@pirata/domain/lib/time';
import { parseQuantity } from '@pirata/domain/lib/money';
import type { ModuleProps } from '../services/moduleProps';
import { WorkDialog } from '../features/tasks-time/WorkDialog';
import { WorkForm } from '../features/tasks-time/WorkForm';
import { FilesPanel } from '../features/collaboration';
import { TaskEditor, TaskChecklist } from '../features/tasks-time';
import { ScheduleTaskDialog } from '../features/planning';
import { ExpenseForm } from '../features/spending';
import { MaterialDetail, MaintenanceDetail } from '../features/inventory';
import { FollowUpForm } from '../features/clients-projects/forms';
export type Dialog = {kind:'quick'|'task-new'|'expense'|'task'|'task-edit'|'plan'|'time'|'time-edit'|'manual'|'material'|'maintenance'|'adjustment'|'lead'|'follow-up'|'objectives';id?:string;projectId?:string;parentTaskId?:string;fromQuick?:boolean;focusChoice?:string}|{kind:'action';title:string;command:BusinessCommand;description:string};
type Props={app:ModuleProps;dialog:Dialog;open(d:Dialog|null,confirmedClose?:boolean):void;now:number};
export function LiveDialogs({app,dialog:d,open,now}:Props){
 const leadName=useRef('');
 // Cancel goes up one Add level; a confirmed save still returns to the workspace.
 const fromQuick='fromQuick' in d&&d.fromQuick, backLabel=fromQuick?'Back to Add menu':undefined;
 const done=()=>open(null),close=()=>open(fromQuick?{kind:'quick',focusChoice:d.kind,projectId:d.projectId,parentTaskId:d.parentTaskId}:null,true),task=app.snapshot.tasks.find(t=>'id' in d&&t.id===d.id),selection='id' in d?d.id:undefined;
 if(d.kind==='task-new'||d.kind==='task-edit')return <TaskEditor {...app} selection={{taskId:d.kind==='task-edit'?d.id:undefined,projectId:d.projectId}} onClose={close} parentTaskId={d.parentTaskId} backLabel={backLabel} onDone={done}/>;
 if(d.kind==='expense')return <ExpenseForm {...app} selection={{expenseId:d.id,projectId:d.projectId}} onClose={close} backLabel={backLabel} onDone={done}/>;
 if(d.kind==='plan')return <ScheduleTaskDialog {...app} selection={{taskId:d.id}} onClose={close}/>;
 if(d.kind==='material')return <MaterialDetail {...app} selection={{materialId:d.id}} onClose={close}/>;
 if(d.kind==='maintenance')return <MaintenanceDetail {...app} selection={{maintenanceId:d.id}} onClose={close}/>;
 if(d.kind==='action')return <WorkDialog title={d.title} onClose={close}><WorkForm app={app} initial={{startedAt:new Date(app.snapshot.runningTimer?.startedAt??now).toISOString()}} command={v=>d.command.type==='timer.correctStart'?{...d.command,startedAt:Date.parse(v.startedAt)}:d.command} message={d.title+' saved.'} done={done} submitLabel={'Confirm '+d.title.toLowerCase()}>{draft=><><p>{d.description}</p>{d.command.type==='timer.correctStart'&&draft.field('startedAt','Corrected start (ISO timestamp)',{hint:'Include Z or an explicit timezone offset. Server time: '+new Date(now).toISOString()})}</>}</WorkForm></WorkDialog>;
 if(d.kind==='quick')return <WorkDialog title="Quick Add" onClose={close} initialFocusSelector={d.focusChoice?'[data-quick-kind="'+d.focusChoice+'"]':undefined}><div className="quick-choices">{([['task-new','Task','Plan a piece of work'],['expense','Expense','Record a purchase'],['manual','Time entry','Record completed work'],['adjustment','Material adjustment','Restock, usage or correction'],['lead','Lead','Keep a new enquiry']] as const).filter(([kind])=>kind!=='expense'||app.snapshot.currentUser?.role!=='employee').map(([kind,title,detail])=>{const Icon=kind==='task-new'?ClipboardList:kind==='expense'?CircleDollarSign:kind==='manual'?Clock3:kind==='adjustment'?PackagePlus:UserPlus;return <button key={kind} data-quick-kind={kind} onClick={()=>open({kind,fromQuick:true,projectId:d.projectId,parentTaskId:d.parentTaskId})}><Icon size={22} aria-hidden="true"/><span><strong>{title}</strong><small>{detail}</small></span><ChevronRight size={17} aria-hidden="true"/></button>;})}</div></WorkDialog>;
 if(d.kind==='objectives')return <ObjectivesForm app={app} close={close}/>;
 if(d.kind==='task'){
  if(!task)return <WorkDialog title="Task unavailable" onClose={close}><p>Refresh to load the latest records.</p></WorkDialog>;
  const state=toLegacyState(app.snapshot),total=actualTaskTime(state,task.id,now),timer=app.snapshot.runningTimer;
  const status=(status:'open'|'blocked'|'done')=>open({kind:'action',title:status==='open'?'Reopen task':status==='done'?'Finish task':'Block task',command:{type:'task.setStatus',id:task.id,status,expectedSessionId:status!=='open'&&timer&&(timer.taskId===task.id||status==='done'&&app.snapshot.tasks.some(t=>t.id===timer.taskId&&t.parentTaskId===task.id))?timer.sessionId:null},description:status==='open'?'Reopen this task and retain its time history?':status==='done'?'Complete this task and its remaining subtasks, and save your active work interval if applicable?':'Mark this task as blocked and save your active work interval, if applicable?' });
  const isRunning=timer?.taskId===task.id;
  const timerTitle=isRunning?'Pause timer':timer?'Switch timer':'Start timer';
  const timerCommand:BusinessCommand=isRunning?{type:'timer.pause',expectedSessionId:timer.sessionId}:timer?{type:'timer.switch',taskId:task.id,expectedSessionId:timer.sessionId}:{type:'timer.start',taskId:task.id};
  return <WorkDialog title="Task details" className="task-detail-dialog" onClose={close}>
    <div className="task-detail-intro"><h3>{task.title}</h3><p className="task-detail-context">{app.snapshot.projects.find(p=>p.id===task.projectId)?.name??'Unfiled'} · {task.assigneeId?'Assigned to '+(app.snapshot.team?.find(person=>person.id===task.assigneeId)?.name??'team member'):'Unassigned'}</p>{task.status!=='open'&&<span className={'badge badge-'+task.status}>{task.status==='done'?'Complete':'Blocked'}</span>}{task.note&&<p className="task-detail-note">{task.note}</p>}</div>
    <TaskChecklist {...app} parentTaskId={task.parentTaskId??task.id}/>
    <section className="task-detail-timer" aria-label="Task time tracking"><h3>Time tracking</h3><div className="task-detail-time-row"><strong>{isRunning&&now<timer.startedAt?'Clock correction needed':formatClock(isRunning?now-timer.startedAt:total)}</strong>{task.status==='open'&&<button className="task-primary" disabled={Boolean(isRunning&&now<timer.startedAt)} onClick={()=>open({kind:'action',title:timerTitle,command:timerCommand,description:isRunning?'Save this work interval and pause the timer?':timer?'Save your current interval and start work on '+task.title+'?':'Start work on '+task.title+'? Your timer continues until you pause or finish.'})}>{isRunning?<Pause size={17} aria-hidden="true"/>:<Play size={17} aria-hidden="true"/>}{timerTitle}</button>}</div><p>{formatDuration(total)} logged{task.estimatedMinutes>0?' · '+formatDuration(task.estimatedMinutes*60000)+' estimated':''}</p>{estimateVariance(task,total)&&<p>{estimateVariance(task,total)}</p>}</section>
    <div className="task-detail-primary">{task.status==='open'?<button onClick={()=>status('done')}><Check size={17} aria-hidden="true"/>Finish task</button>:<button onClick={()=>status('open')}>Reopen task</button>}</div>
    <div className="task-detail-tools"><button onClick={()=>open({kind:'task-edit',id:task.id})}><Pencil size={16} aria-hidden="true"/>Edit task</button><button onClick={()=>open({kind:'plan',id:task.id})}><CalendarDays size={16} aria-hidden="true"/>Schedule / reschedule</button><button onClick={()=>open({kind:'time',id:task.id})}><Clock3 size={16} aria-hidden="true"/>Time entries</button>{!task.parentTaskId&&<button onClick={()=>open({kind:'task-new',parentTaskId:task.id,projectId:task.projectId??undefined})}><Plus size={16} aria-hidden="true"/>Add subtask</button>}</div>
    <FilesPanel app={app} parentType="task" parentId={task.id}/>
    {task.status==='open'&&<details className="task-secondary-actions"><summary>More task actions</summary><button onClick={()=>status('blocked')}>Block task</button></details>}
  </WorkDialog>;
 }
 if(d.kind==='time')return <WorkDialog title="Time entries" onClose={close}><p>{task?.title??'All tasks'}. Correct a recorded entry explicitly; the original session is never counted twice.</p><button onClick={()=>open({kind:'manual',id:d.id})}>Add manual time</button><ul className="live-records">{app.snapshot.timeEntries.filter(e=>!d.id||e.taskId===d.id).map(e=><li key={e.id}><strong>{formatDuration(entryMilliseconds(e))}</strong><p>{e.source==='manual'?e.date+' · Manual':new Date(e.startedAt).toISOString()+' → '+new Date(e.endedAt).toISOString()}</p><p>{e.note}</p><button onClick={()=>open({kind:'time-edit',id:e.id})}>Correct entry</button></li>)}</ul></WorkDialog>;
 if(d.kind==='manual'||d.kind==='time-edit')return <TimeForm app={app} entry={d.kind==='time-edit'?app.snapshot.timeEntries.find(e=>e.id===d.id):undefined} taskId={d.kind==='manual'?d.id:undefined} close={close} done={done} backLabel={backLabel}/>;
 if(d.kind==='adjustment')return <WorkDialog title="Material adjustment" onClose={close} backLabel={backLabel}><WorkForm app={app} initial={{materialId:d.id??app.snapshot.materials[0]?.id??'',deltaMinor:'',reason:'restock',note:''}} command={v=>({type:'material.adjust',materialId:v.materialId,deltaMinor:parseQuantity(v.deltaMinor)??NaN,reason:v.reason as 'restock'|'usage'|'correction',note:v.note})} validate={(v):Record<string,string>=>{const m=app.snapshot.materials.find(m=>m.id===v.materialId),q=parseQuantity(v.deltaMinor);return q===null||q===0?{deltaMinor:'Enter a nonzero signed quantity with at most two decimals.'}:m?.unit==='piece'&&q%100!==0?{deltaMinor:'Pieces require whole units.'}:{};}} message="Material stock updated. Spending is unchanged." done={done}>{f=><><p>Quantity changes do not record purchases. Add an expense separately.</p>{f.field('materialId','Material',{options:app.snapshot.materials.map(m=>({value:m.id,label:m.name+' ('+m.unit+')'}))})}{f.field('deltaMinor','Signed quantity adjustment',{hint:'Use a minus sign for usage. Stock cannot fall below reservations.'})}{f.field('reason','Reason',{options:['restock','usage','correction'].map(value=>({value,label:value}))})}{f.field('note','Note (optional)',{type:'textarea'})}{!app.snapshot.materials.length&&<p>Add a material in Inventory first.</p>}</>}</WorkForm></WorkDialog>;
 if(d.kind==='lead')return <WorkDialog title="Add lead" onClose={close} backLabel={backLabel}><WorkForm app={{...app,onSaved:()=>app.onSaved('Lead saved: '+leadName.current)}} initial={{name:'',phone:'',email:'',workDescription:'',nextFollowUpDate:''}} command={v=>{leadName.current=v.name.trim();return {type:'lead.create',name:v.name,phone:v.phone,email:v.email.trim(),workDescription:v.workDescription,nextFollowUpDate:v.nextFollowUpDate||null};}} message="Lead saved." done={done}>{f=><>{f.field('name','Name')}{f.field('phone','Phone (optional)',{type:'tel'})}{f.field('email','Email (optional)',{type:'email'})}{f.field('workDescription','Work description')}{f.field('nextFollowUpDate','Follow-up date (optional)',{type:'date'})}<p>The lead stays in Clients → Leads, including when no reminder is due.</p></>}</WorkForm></WorkDialog>;
 if(d.kind==='follow-up'){const lead=app.snapshot.leads.find(l=>l.id===selection);return <WorkDialog title="Client follow-up" onClose={close}>{lead?<><h3>{lead.name}</h3><p>{lead.workDescription}</p><p>{lead.phone||'No phone'} · {lead.email||'No email'}</p><FollowUpForm app={app} lead={lead} done={done}/></>:<p>Lead unavailable.</p>}</WorkDialog>;}
 return null;
}
function TimeForm({app,entry,taskId,close,done,backLabel}:{app:ModuleProps;entry?:TimeEntry;taskId?:string;close():void;done():void;backLabel?:string}){return <WorkDialog title={entry?'Correct time entry':'Add time entry'} onClose={close} backLabel={backLabel}><WorkForm app={app} initial={{taskId:entry?.taskId??taskId??app.snapshot.tasks[0]?.id??'',date:entry?.source==='manual'?entry.date:app.businessDate,minutes:String(entry?.source==='manual'?entry.durationSeconds/60:30),note:entry?.note??'',startedAt:entry?.source==='timer'?new Date(entry.startedAt).toISOString():'',endedAt:entry?.source==='timer'?new Date(entry.endedAt).toISOString():''}} command={v=>entry?{type:'timeEntry.correct',id:entry.id,correction:entry.source==='timer'?{source:'timer',startedAt:Date.parse(v.startedAt),endedAt:Date.parse(v.endedAt),note:v.note}:{source:'manual',date:v.date,minutes:Number(v.minutes),note:v.note}}:{type:'timeEntry.createManual',taskId:v.taskId,date:v.date,minutes:Number(v.minutes),note:v.note}} message={entry?'Time entry corrected.':'Time entry added.'} done={done}>{f=><>{!entry&&f.field('taskId','Task',{options:app.snapshot.tasks.map(t=>({value:t.id,label:t.title}))})}{entry?.source==='timer'?<>{f.field('startedAt','Start (ISO timestamp)')}{f.field('endedAt','End (ISO timestamp)')}</>:<>{f.field('date','Work date',{type:'date'})}{f.field('minutes','Duration in whole minutes',{type:'number'})}</>}{f.field('note','Note (optional)',{type:'textarea'})}</>}</WorkForm></WorkDialog>;}
function ObjectivesForm({app,close}:{app:ModuleProps;close():void}){
 const [editingDate]=useState(app.businessDate);
 const objectives=app.snapshot.objectives.filter(o=>o.date===editingDate).sort((a,b)=>a.rank-b.rank),initial:Record<string,string>={count:String(objectives.length)};
 const keys=['id','title','taskId','status','note'] as const;objectives.forEach((o,i)=>keys.forEach(k=>{initial[`objectives.${i}.${k}`]=o[k]??'';}));
 return <WorkDialog title="Edit objectives" onClose={close}><WorkForm app={app} initial={initial} command={v=>({type:'objectives.replaceForDate',date:editingDate,objectives:Array.from({length:Number(v.count)},(_,i)=>({id:v[`objectives.${i}.id`],title:v[`objectives.${i}.title`],taskId:v[`objectives.${i}.taskId`]||null,status:v[`objectives.${i}.status`] as 'open'|'partial'|'blocked'|'done',note:v[`objectives.${i}.note`],rank:i}))})} message="Today's objectives saved." done={close}>{f=><><p>Up to three outcomes for {editingDate}. Task completion is separate.</p>{Array.from({length:Number(f.values.count)},(_,i)=><fieldset key={f.values[`objectives.${i}.id`]} className="objective-editor"><legend>Objective {i+1}</legend>{f.field(`objectives.${i}.title`,`Objective ${i+1} title`)}{f.field(`objectives.${i}.taskId`,`Objective ${i+1} task`,{options:[{value:'',label:'No linked task'},...app.snapshot.tasks.map(t=>({value:t.id,label:t.title}))]})}{f.field(`objectives.${i}.status`,`Objective ${i+1} status`,{options:['open','partial','blocked','done'].map(value=>({value,label:value}))})}{f.field(`objectives.${i}.note`,`Objective ${i+1} note`,{type:'textarea',hint:'Explain the reason when blocked.'})}<div className="live-actions">{[-1,1].map(delta=><button key={delta} type="button" data-dirty disabled={i+delta<0||i+delta>=Number(f.values.count)} onClick={()=>{const v={...f.values};for(const k of keys){v[`objectives.${i}.${k}`]=f.values[`objectives.${i+delta}.${k}`];v[`objectives.${i+delta}.${k}`]=f.values[`objectives.${i}.${k}`];}f.replace(v);}}>{delta<0?'Up':'Down'}</button>)}<button type="button" data-dirty onClick={()=>{const v:Record<string,string>={...f.values,count:String(Number(f.values.count)-1)};for(let n=i;n<Number(v.count);n++)for(const k of keys)v[`objectives.${n}.${k}`]=f.values[`objectives.${n+1}.${k}`];f.replace(v);}}>Remove</button></div></fieldset>)}<button type="button" data-dirty disabled={Number(f.values.count)>=3} onClick={()=>{const i=Number(f.values.count);f.replace({...f.values,count:String(i+1),[`objectives.${i}.id`]:crypto.randomUUID(),[`objectives.${i}.title`]:'',[`objectives.${i}.taskId`]:'',[`objectives.${i}.status`]:'open',[`objectives.${i}.note`]:''});}}>Add objective</button></>}</WorkForm></WorkDialog>;
}
