import type { Strings } from '../../i18n';
export const strings:Strings={
  en:{'sales.title':'Sales details','sales.edit':'Edit','sales.start':'Start date','sales.end':'End date','sales.note':'Sales note','sales.save':'Save','sales.saved':'Sales details saved.','sales.statusSaved':'Project status saved.',
    'sales.draftHint':'Draft: only the office sees it until it is sent to review.','sales.sendToReview':'Send to review','sales.sentBack':'Sent back: {note}','sales.reviewHint':'Sold: review the scope before the crew sees it.','sales.approve':'Approve for scheduling','sales.sendBack':'Send back','sales.sendBackNote':'What is missing?','sales.sendBackConfirm':'Send back to draft','sales.waitingReview':'Waiting for a manager to review this project.',
    'sales.capture.title':'New project','sales.capture.intro':'Client and a name are enough to start. Add tasks while you walk the job.','sales.capture.client':'Client','sales.capture.clientName':'New client name','sales.capture.clientPhone':'Client phone','sales.capture.existingClient':'Choose an existing client','sales.capture.newClient':'New client','sales.capture.projectName':'Project name','sales.capture.projectPlaceholder':'Smith back deck','sales.capture.address':'Job address (optional)','sales.capture.start':'Start walking the job','sales.capture.need':'Choose a client and give the project a name.',
    'sales.capture.walkHint':'Type each step as you say it. Photos attach to the project or to a task.','sales.capture.projectPhotos':'Project photos','sales.capture.taskPlaceholder':'e.g. Pressure wash the deck','sales.capture.addTask':'Add','sales.capture.rename':'New name','sales.capture.renameShort':'Rename','sales.capture.subtask':'Subtask','sales.capture.subtaskPlaceholder':'e.g. Cover the pool','sales.capture.photo':'Photo','sales.capture.remove':'Remove','sales.capture.removeConfirm':'Remove “{title}”?','sales.capture.noTasks':'No tasks yet. Add the first step.','sales.capture.saveDraft':'Save as draft','sales.capture.done':'Done','sales.capture.repHint':'You can keep editing the draft until it is sent to review.'},
  es:{'sales.title':'Datos de venta','sales.edit':'Editar','sales.start':'Fecha de inicio','sales.end':'Fecha de fin','sales.note':'Nota de venta','sales.save':'Guardar','sales.saved':'Datos de venta guardados.','sales.statusSaved':'Estado del proyecto guardado.',
    'sales.draftHint':'Borrador: solo la oficina lo ve hasta que se envía a revisión.','sales.sendToReview':'Enviar a revisión','sales.sentBack':'Devuelto: {note}','sales.reviewHint':'Vendido: revisa el alcance antes de que lo vea la cuadrilla.','sales.approve':'Aprobar para programar','sales.sendBack':'Devolver','sales.sendBackNote':'¿Qué falta?','sales.sendBackConfirm':'Devolver a borrador','sales.waitingReview':'Esperando que un manager revise este proyecto.',
    'sales.capture.title':'Proyecto nuevo','sales.capture.intro':'Con el cliente y un nombre basta para empezar. Agrega tareas mientras recorres el trabajo.','sales.capture.client':'Cliente','sales.capture.clientName':'Nombre del cliente nuevo','sales.capture.clientPhone':'Teléfono del cliente','sales.capture.existingClient':'Elegir un cliente existente','sales.capture.newClient':'Cliente nuevo','sales.capture.projectName':'Nombre del proyecto','sales.capture.projectPlaceholder':'Deck de la familia Smith','sales.capture.address':'Dirección (opcional)','sales.capture.start':'Empezar a recorrer el trabajo','sales.capture.need':'Elige un cliente y ponle nombre al proyecto.',
    'sales.capture.walkHint':'Escribe cada paso mientras lo dices. Las fotos se guardan en el proyecto o en una tarea.','sales.capture.projectPhotos':'Fotos del proyecto','sales.capture.taskPlaceholder':'p. ej. Lavar a presión el deck','sales.capture.addTask':'Agregar','sales.capture.rename':'Nuevo nombre','sales.capture.renameShort':'Renombrar','sales.capture.subtask':'Subtarea','sales.capture.subtaskPlaceholder':'p. ej. Cubrir la piscina','sales.capture.photo':'Foto','sales.capture.remove':'Quitar','sales.capture.removeConfirm':'¿Quitar “{title}”?','sales.capture.noTasks':'Aún no hay tareas. Agrega el primer paso.','sales.capture.saveDraft':'Guardar como borrador','sales.capture.done':'Listo','sales.capture.repHint':'Puedes seguir editando el borrador hasta enviarlo a revisión.'},
};
