import type { Strings } from '../../i18n';
export const strings:Strings={
  en:{'trash.delete':'Delete','trash.confirm':'Delete “{label}”? It moves to Deleted items, where the owner or a manager can restore it.','trash.deleted':'Deleted. The owner or a manager can restore it from Menu → Deleted items.','trash.restore':'Restore','trash.restored':'Restored.',
    'trash.intro':'Deleted records stay here until someone restores them. Nothing is destroyed, and anything deleted with a project, task or tool comes back with it.','trash.empty':'Nothing has been deleted.','trash.by':'Deleted by {name} · {time}','trash.cascaded':'{count} linked items come back with it',
    'trash.kind.project':'Project','trash.kind.task':'Task','trash.kind.client':'Client','trash.kind.lead':'Lead','trash.kind.expense':'Purchase','trash.kind.materialRequest':'Material request','trash.kind.toolSignOut':'Tool sign-out','trash.kind.question':'Question','trash.kind.shift':'Hours entry','trash.kind.taskTemplate':'Task template','trash.kind.projectTemplate':'Project template','trash.kind.equipment':'Equipment','trash.kind.material':'Material','trash.kind.maintenance':'Maintenance','trash.kind.equipmentReport':'Broken report','trash.kind.projectNote':'Note'},
  es:{'trash.delete':'Eliminar','trash.confirm':'¿Eliminar “{label}”? Pasa a Elementos eliminados, donde el dueño o un encargado puede recuperarlo.','trash.deleted':'Eliminado. El dueño o un encargado puede recuperarlo en Menú → Elementos eliminados.','trash.restore':'Recuperar','trash.restored':'Recuperado.',
    'trash.intro':'Lo eliminado se queda aquí hasta que alguien lo recupere. Nada se destruye, y lo que se eliminó junto con un proyecto, una tarea o una herramienta vuelve con ellos.','trash.empty':'No se ha eliminado nada.','trash.by':'Eliminado por {name} · {time}','trash.cascaded':'{count} elementos ligados vuelven con él',
    'trash.kind.project':'Proyecto','trash.kind.task':'Tarea','trash.kind.client':'Cliente','trash.kind.lead':'Prospecto','trash.kind.expense':'Compra','trash.kind.materialRequest':'Pedido de material','trash.kind.toolSignOut':'Préstamo de herramienta','trash.kind.question':'Pregunta','trash.kind.shift':'Registro de horas','trash.kind.taskTemplate':'Plantilla de tarea','trash.kind.projectTemplate':'Plantilla de proyecto','trash.kind.equipment':'Equipo','trash.kind.material':'Material','trash.kind.maintenance':'Mantenimiento','trash.kind.equipmentReport':'Reporte de avería','trash.kind.projectNote':'Nota'},
};
