import { useState } from 'react';
import { ChevronLeft, ChevronRight, Download } from 'lucide-react';
import type { ModuleProps } from '../../services/moduleProps';
import { useT, useLocale } from '../../i18n';
import { formatTime } from '../../i18n/locale';
import { TranslatedText } from '../../components/TranslatedText';
import { useCan } from '../../state/permissions';
import { DateField, addDays } from '../../components/DateField';
import { Money } from '../../components/Money';
import { runCommand } from '../work/commands';
import { reportData } from './selectors';
import '../hours/styles.css';
const clock = (minute: number | null) => minute === null ? '' : String(Math.floor(minute / 60)).padStart(2, '0') + ':' + String(minute % 60).padStart(2, '0');
function Section({ title, count, children, open = true }: { title: string; count: number; children: React.ReactNode; open?: boolean }) {
  return <details className="report-section card" open={open}><summary>{title}<span className="directory-count">{count}</span></summary>{children}</details>;
}
/** One day, everyone's work (R-REPORT-1). Everyone can open it; money renders only with money.costs. */
export function ReportView(app: ModuleProps & { date?: string }) {
  const t = useT(), locale = useLocale(), money = useCan('money.costs'), snapshot = app.snapshot, me = snapshot.currentUser?.id ?? '';
  const [date, setDate] = useState(app.date ?? app.businessDate), [projectId, setProjectId] = useState(''), [userId, setUserId] = useState('');
  const data = reportData(snapshot, { date, projectId: projectId || undefined, userId: userId || undefined });
  const team = snapshot.team ?? [], projects = snapshot.projects;
  const name = (id: string | null | undefined) => team.find(m => m.id === id)?.name ?? '—', project = (id: string | null | undefined) => projects.find(p => p.id === id)?.name ?? '—', tool = (id: string) => snapshot.equipment.find(e => e.id === id)?.name ?? '—';
  const myNote = (snapshot.dayNotes ?? []).find(note => note.userId === me && note.date === date);
  const [draft, setDraft] = useState<string | null>(null), [busy, setBusy] = useState(false);
  const saveNote = async () => { if (draft === null) return; setBusy(true); const message = await runCommand(app, { type: 'dayNote.save', date, body: draft.trim() }); setBusy(false); if (message) app.onSaved(message); else { app.onSaved(t('report.noteSaved')); setDraft(null); } };
  const completedByProject = data.completed.reduce<Record<string, typeof data.completed>>((groups, task) => { (groups[task.projectId ?? ''] ??= []).push(task); return groups; }, {});
  return <section className="work-module report-view" aria-label={t('shell.view.report')}>
    <div className="day-date"><button type="button" aria-label={t('work.previousDay')} onClick={() => setDate(addDays(date, -1))}><ChevronLeft size={18} aria-hidden="true" /></button><DateField label={t('work.date')} value={date} onChange={setDate} /><button type="button" aria-label={t('work.nextDay')} onClick={() => setDate(addDays(date, 1))}><ChevronRight size={18} aria-hidden="true" /></button><a className="work-link-button" href={'/api/v1/export/daily-report.csv?date=' + date} download><Download size={15} aria-hidden="true" />{t('hours.export')}</a></div>
    <div className="report-filters"><label className="work-field">{t('report.project')}<select value={projectId} onChange={e => setProjectId(e.target.value)}><option value="">{t('report.allProjects')}</option>{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="work-field">{t('report.person')}<select value={userId} onChange={e => setUserId(e.target.value)}><option value="">{t('report.everyone')}</option>{team.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label></div>
    <Section title={t('report.completed')} count={data.completed.length}>{!data.completed.length && <p className="muted">{t('report.nothing')}</p>}{Object.entries(completedByProject).map(([pid, tasks]) => <div key={pid}><h4>{project(pid)}</h4><ul>{tasks.map(task => <li key={task.id} className={task.parentTaskId ? 'is-step' : ''}><button type="button" className="work-link-button" onClick={() => app.onOpenTask(task.id)}><TranslatedText kind="task" id={task.id} field="title" text={task.title} compact /></button><small>{t('report.by', { name: name(task.completedBy), time: formatTime(locale, task.completedAt ?? 0) })}{task.parentTaskId ? ' · ' + t('report.step') : ''}</small></li>)}</ul></div>)}</Section>
    <Section title={t('report.hours')} count={data.shifts.length}>{!data.shifts.length && !data.missingHours.length && <p className="muted">{t('report.nothing')}</p>}<ul>{data.shifts.map(shift => <li key={shift.id}>{name(shift.userId)} · {project(shift.projectId)} · {shift.kind === 'hours' ? clock(shift.startMinute) + '–' + clock(shift.endMinute) : (shift.daysMinor ?? 0) / 100 + ' d'} · <strong>{(shift.minutes / 60).toFixed(2)} h</strong><small>{t('hours.status.' + shift.status)}{shift.note ? ' · ' + shift.note : ''}</small></li>)}{data.missingHours.map(row => <li key={row.userId + row.projectId} className="is-warning">{name(row.userId)} · {project(row.projectId)}<small>{t('report.noHours')}</small></li>)}</ul></Section>
    <Section title={t('report.notes')} count={data.notes.length}>{!data.notes.length && <p className="muted">{t('report.nothing')}</p>}<ul>{data.notes.map(note => <li key={note.id}><strong>{name(note.userId)}</strong><TranslatedText kind="dayNote" id={note.id} field="body" text={note.body} as="p" className="day-note" /></li>)}</ul></Section>
    <Section title={t('report.questions')} count={data.questions.length}>{!data.questions.length && <p className="muted">{t('report.nothing')}</p>}<ul>{data.questions.map(q => <li key={q.id}><button type="button" className="work-link-button" onClick={() => app.onOpenTask(q.taskId)}>{snapshot.tasks.find(task => task.id === q.taskId)?.title ?? '—'}</button> · {project(q.projectId)}<TranslatedText kind="question" id={q.id} field="body" text={q.body} as="p" /><small>{q.answeredAt ? <>{t('report.answered', { name: name(q.answeredBy) })}: <TranslatedText kind="question" id={q.id} field="answer" text={q.answer} compact /></> : t('report.open')} · {name(q.askedBy)}</small></li>)}</ul></Section>
    <Section title={t('report.materials')} count={data.requests.length}>{!data.requests.length && <p className="muted">{t('report.nothing')}</p>}<ul>{data.requests.map(item => <li key={item.id}><TranslatedText kind="materialRequest" id={item.id} field="title" text={item.title} compact />{item.quantity ? ' × ' + item.quantity : ''} · {item.projectId ? project(item.projectId) : name(item.forUserId)}<small>{item.receivedAt ? t('report.received') : t('report.requested')} · {name(item.createdBy)}</small></li>)}</ul></Section>
    <Section title={t('report.tools')} count={data.tools.length + data.broken.length}>{!data.tools.length && !data.broken.length && <p className="muted">{t('report.nothing')}</p>}<ul>{data.tools.map(event => <li key={event.signOut.id + event.kind}>{tool(event.signOut.equipmentId)} · {name(event.signOut.takenBy)}<small>{event.kind === 'taken' ? t('report.taken') : t('report.returned')}{event.signOut.projectId ? ' · ' + project(event.signOut.projectId) : ''}</small></li>)}{data.broken.map(report => <li key={report.id} className="is-warning">{tool(report.equipmentId)}: <TranslatedText kind="equipmentReport" id={report.id} field="body" text={report.body} compact /><small>{t('report.broken')} · {name(report.reportedBy)}</small></li>)}</ul></Section>
    {money && <Section title={t('report.money')} count={data.expenses.length + data.labor.length}>{!data.expenses.length && !data.labor.length && <p className="muted">{t('report.nothing')}</p>}<ul>{data.expenses.map(expense => <li key={expense.id}>{expense.description} · {expense.projectId ? project(expense.projectId) : t('report.general')}<small>{expense.category} · <Money cents={expense.amountCents} /></small></li>)}{data.labor.map(row => <li key={row.projectId}>{t('report.labor')} · {project(row.projectId)}<small>{(row.minutes / 60).toFixed(2)} h · <Money cents={row.cents} /></small></li>)}</ul></Section>}
    <section className="card"><h3>{t('report.myNote')}</h3><p className="muted">{t('report.myNoteHint')}</p><textarea rows={3} value={draft ?? myNote?.body ?? ''} onChange={e => setDraft(e.target.value)} /><div className="live-actions"><button type="button" className="work-primary" disabled={busy || draft === null} onClick={() => void saveNote()}>{t('report.saveNote')}</button></div></section>
  </section>;
}
