import { tx } from '../../i18n';
import { useId, useState } from 'react';
import { isOfficeRole } from '@pirata/contracts/permissions';
import { Check, Clock3, History, Settings2, Sparkles, Wrench } from 'lucide-react';
import type { CleanupObligation } from '@pirata/contracts/index';
import type { ModuleProps } from '../../services/moduleProps';
import { ActionStatus, useCommand } from './actions';
import './styles.css';
const display = (at: number) => new Intl.DateTimeFormat('en-US', { timeZone: 'America/New_York', dateStyle: 'medium', timeStyle: 'short' }).format(at);
const localValue = (at: number) => { const p = Object.fromEntries(new Intl.DateTimeFormat('en-CA', { timeZone: 'America/New_York', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).formatToParts(at).map(p => [p.type, p.value])); return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`; };
/** datetime-local is explicitly labelled business time, regardless of the phone's zone. */
function businessTimestamp(value: string) { const [date, time] = value.split('T'); if (!date || !time) return NaN; const [year, month, day] = date.split('-').map(Number), [hour, minute] = time.split(':').map(Number), wall = Date.UTC(year, month - 1, day, hour, minute); let at = wall; for (let i = 0; i < 4; i++) { const [d, t] = localValue(at).split('T'), [y, m, a] = d.split('-').map(Number), [h, n] = t.split(':').map(Number); at += wall - Date.UTC(y, m - 1, a, h, n); } return localValue(at) === value ? at : NaN; }
function CleanupItem({ app, item }: { app: ModuleProps; item: CleanupObligation }) {
  const action = useCommand(app), [snooze, setSnooze] = useState(false), [due, setDue] = useState(''), [error, setError] = useState(''), id = useId();
  const tool = app.snapshot.equipment.find(e => e.id === item.equipmentId), responsible = app.snapshot.team?.find(p => p.id === item.userId)?.name ?? 'Team member';
  const postponements = (app.snapshot.cleanupSnoozes ?? []).filter(s => s.obligationId === item.id).sort((a, b) => b.createdAt - a.createdAt);
  return <li className="co-cleanup-item"><h4>Clean {tool?.name ?? 'equipment'}</h4><div className="co-heading"><span className="co-person"><span className="co-avatar" aria-hidden="true">{responsible.slice(0, 1)}</span><strong>{responsible}</strong></span><span className="co-meta"><Clock3 size={14} aria-hidden="true" />{item.cleaningMinutes} min planned</span></div><p className="co-cleanup-due">{item.completedAt === null ? (item.dueAt < app.snapshot.serverNow ? 'Needs attention · ' : 'Due · ') + display(item.dueAt) : 'Cleaned · ' + display(item.completedAt)}</p><small>Latest safe cleaning: {display(item.deadlineAt)}. Estimated minutes do not record worked time.</small>
    {item.completedAt === null && <><div className="co-actions"><button type="button" className="primary" disabled={action.busy || action.uncertain} onClick={() => void action.run({ type: 'cleanup.complete', id: item.id }, () => app.onSaved('Cleaning recorded.'))}><Check size={16} aria-hidden="true" />{tx('Mark cleaned')}</button><button type="button" disabled={action.busy || action.uncertain || item.dueAt >= item.deadlineAt || item.deadlineAt <= app.snapshot.serverNow} aria-expanded={snooze} onClick={() => setSnooze(!snooze)}><Clock3 size={16} aria-hidden="true" />{tx('Snooze')}</button></div>{snooze && <form onSubmit={event => { event.preventDefault(); const dueAt = businessTimestamp(due); if (!Number.isFinite(dueAt) || dueAt <= Math.max(item.dueAt, app.snapshot.serverNow) || dueAt > item.deadlineAt) { setError('Choose a later time within the fixed cleaning deadline.'); return; } setError(''); void action.run({ type: 'cleanup.snooze', id: item.id, dueAt }, () => { setSnooze(false); app.onSaved('Cleaning reminder postponed. The deadline is unchanged.'); }); }}><label htmlFor={id}>{tx('New reminder (America/New_York)')}<input id={id} type="datetime-local" value={due} min={localValue(Math.max(item.dueAt, app.snapshot.serverNow) + 60000)} max={localValue(item.deadlineAt)} onChange={e => setDue(e.target.value)} required /></label><p>{responsible} remains responsible. The maximum deadline cannot move.</p><button disabled={action.busy || action.uncertain} type="submit">{tx('Save snooze')}</button>{error && <p role="alert" className="co-error">{error}</p>}</form>}</>}
    {postponements.length > 0 && <details><summary>Postponement history ({postponements.length})</summary><ul>{postponements.map(s => <li key={s.id}>{app.snapshot.team?.find(p => p.id === s.userId)?.name ?? 'Team member'} postponed at {display(s.createdAt)} to {display(s.toDueAt)}.</li>)}</ul></details>}<ActionStatus action={action} /></li>;
}
export function CleanupPanel({ app, equipmentId, userId }: { app: ModuleProps; equipmentId?: string; userId?: string }) {
  // Reminders are per person (update 2026-09-25): the panel shows mine by default; the office can switch to everyone.
  const [history, setHistory] = useState(false), [everyone, setEveryone] = useState(false);
  const me = app.snapshot.currentUser?.id, office = isOfficeRole(app.snapshot.currentUser?.role), person = userId ?? (everyone && office ? undefined : me);
  const items = (app.snapshot.cleanupObligations ?? []).filter(item => (!equipmentId || item.equipmentId === equipmentId) && (!person || item.userId === person) && (history || item.completedAt === null)).sort((a, b) => Number(a.completedAt !== null) - Number(b.completedAt !== null) || a.dueAt - b.dueAt);
  return <section className="co-panel co-cleanup-panel" aria-label={tx('Cleanup reminders')}><header className="co-heading"><div className="co-section-title"><span className="co-section-icon"><Sparkles size={20} aria-hidden="true" /></span><h3>{tx('Cleanup')}</h3></div>{office && !userId && <button className="co-quiet" type="button" aria-pressed={everyone} onClick={() => setEveryone(!everyone)}>{everyone ? 'Everyone' : 'Mine'}</button>}<button className="co-quiet" type="button" aria-pressed={history} onClick={() => setHistory(!history)}><History size={15} aria-hidden="true" />{history ? 'Show open reminders' : 'Cleaning history'}</button></header><ul className="co-list">{items.map(item => <CleanupItem key={item.id} app={app} item={item} />)}</ul>{!items.length && <div className="co-empty"><Sparkles size={24} aria-hidden="true" /><p>{history ? 'No cleaning history yet.' : 'All clear for now.'}<small>{tx('Recording equipment use starts a cleaning reminder when its rule is set.')}</small></p></div>}</section>;
}
export function EquipmentCleanup({ app, equipmentId }: { app: ModuleProps; equipmentId: string }) {
  const tool = app.snapshot.equipment.find(e => e.id === equipmentId), action = useCommand(app), [minutes, setMinutes] = useState(String(tool?.cleaningMinutes ?? '')), [delay, setDelay] = useState(String(tool?.maxCleaningDelayMinutes ?? '')), [task, setTask] = useState(app.snapshot.runningTimer?.taskId ?? ''), [rule, setRule] = useState(false), [error, setError] = useState(''), id = useId();
  if (!tool) return null;
  const configured = tool.cleaningMinutes != null && tool.maxCleaningDelayMinutes != null;
  return <><section className="co-panel" aria-label={tx('Equipment use and cleaning')}><div className="co-section-title"><span className="co-section-icon"><Wrench size={20} aria-hidden="true" /></span><h3>{tx('Use & cleaning rule')}</h3></div><p>{configured ? `Cleaning takes ${tool.cleaningMinutes} minutes; maximum delay ${tool.maxCleaningDelayMinutes} minutes from first use.` : 'Cleanup rule needs setup. Use can still be recorded; no safety interval will be guessed.'}</p><label htmlFor={id + '-task'}>{tx('Work being done (optional)')}<select id={id + '-task'} value={task} onChange={e => setTask(e.target.value)}><option value="">{tx('No linked task')}</option>{app.snapshot.tasks.filter(t => !t.archivedAt && t.status !== 'done').map(t => <option key={t.id} value={t.id}>{t.title}</option>)}</select></label><div className="co-actions"><button className="primary" disabled={action.busy || action.uncertain || tool.archivedAt !== null} type="button" onClick={() => void action.run({ type: 'equipment.use', id: tool.id, taskId: task || null }, () => app.onSaved(configured ? 'Use recorded. One cleaning reminder remains until cleaned.' : 'Use recorded. Set a cleanup rule before the next use.'))}><Wrench size={16} aria-hidden="true" />{tx('Record use')}</button><button type="button" aria-expanded={rule} onClick={() => setRule(!rule)}><Settings2 size={16} aria-hidden="true" />{configured ? 'Edit cleanup rule' : 'Set cleanup rule'}</button></div>
    {rule && <form className="co-cleanup-rule" onSubmit={e => { e.preventDefault(); const cleaningMinutes = Number(minutes), maxCleaningDelayMinutes = Number(delay); if (!Number.isInteger(cleaningMinutes) || cleaningMinutes < 1 || cleaningMinutes > 1440 || !Number.isInteger(maxCleaningDelayMinutes) || maxCleaningDelayMinutes < 1 || maxCleaningDelayMinutes > 525600) { setError('Enter cleaning minutes from 1 to 1440 and maximum delay from 1 to 525600 minutes.'); return; } setError(''); void action.run({ type: 'equipment.cleanupRule', id: tool.id, cleaningMinutes, maxCleaningDelayMinutes }, () => setRule(false)); }} data-save-phase={action.busy ? 'saving' : action.uncertain ? 'uncertain' : 'editing'}><fieldset disabled={action.busy || action.uncertain}><label htmlFor={id + '-minutes'}>{tx('Cleaning duration (minutes)')}<input id={id + '-minutes'} type="number" inputMode="numeric" min={1} max={1440} value={minutes} onChange={e => setMinutes(e.target.value)} /></label><label htmlFor={id + '-delay'}>{tx('Maximum permitted delay (minutes)')}<input id={id + '-delay'} type="number" inputMode="numeric" min={1} max={525600} value={delay} onChange={e => setDelay(e.target.value)} /></label><p>Follow the equipment and product guidance. A saved rule affects future cycles; existing deadlines remain fixed.</p><button type="submit">{tx('Save cleanup rule')}</button></fieldset>{error && <p role="alert" className="co-error">{error}</p>}</form>}<ActionStatus action={action} /></section><CleanupPanel app={app} equipmentId={equipmentId} /></>;
}
