import { afterEach, expect, it } from 'vitest';
import { createFixture, type Fixture } from '../../helpers/fixture.js';
import { runAs, userOf, type Headers } from '../../helpers/roles.js';
let f: Fixture;
const NOW = 1_790_000_000_000;
afterEach(async () => { await f?.close(); });
const snap = async (headers: Headers) => (await f.app.inject({ url: '/api/v1/snapshot', headers })).json();
async function setup() {
  f = await createFixture({ now: () => NOW });
  const owner = await f.authenticate();
  const worker = await userOf(f, 'worker', owner), manager = await userOf(f, 'manager', owner);
  const client = (await runAs(f, owner, { type: 'client.create', name: 'Smith', phone: '', email: '', note: '' })).json().result.id as string;
  const project = (await runAs(f, owner, { type: 'project.create', name: 'Smith exterior', clientId: client, clientName: '', address: '', note: '' })).json().result.id as string;
  const task = (await runAs(f, owner, { type: 'task.create', title: 'Prime', projectId: project, estimatedMinutes: 0, note: '' })).json().result.id as string;
  const sub = (await runAs(f, owner, { type: 'task.create', title: 'Mask windows', projectId: project, parentTaskId: task, estimatedMinutes: 0, note: '' })).json().result.id as string;
  return { owner, worker, manager, client, project, task, sub };
}
it('deleting a project hides it with its tasks, questions and requests; the Trash restores the whole group', async () => {
  const { owner, worker, client, project, task, sub } = await setup();
  const question = (await runAs(f, worker.headers, { type: 'question.ask', taskId: sub, body: 'Which tape?' })).json().result.id;
  const request = (await runAs(f, worker.headers, { type: 'materialRequest.create', title: 'Tape', taskId: sub })).json().result.id;
  expect((await runAs(f, worker.headers, { type: 'record.delete', kind: 'project', id: project })).statusCode).toBe(403);
  const deleted = await runAs(f, owner, { type: 'record.delete', kind: 'project', id: project });
  expect(deleted.statusCode, deleted.body).toBe(200);
  const after = await snap(owner);
  expect(after.projects).toHaveLength(0); expect(after.tasks).toHaveLength(0); expect(after.taskQuestions).toHaveLength(0); expect(after.shoppingItems).toHaveLength(0);
  expect(after.clients.map((c: { id: string }) => c.id)).toEqual([client]);
  expect(after.trash).toEqual([expect.objectContaining({ kind: 'project', id: project, label: 'Smith exterior', detail: 'Smith', cascaded: 4, deletedBy: f.ownerId, deletedAt: NOW })]);
  expect((await snap(worker.headers)).trash).toBeUndefined();
  expect(f.repo.get('projects', project)).toBeUndefined();
  expect(f.repo.getDeleted('projects', project)?.name).toBe('Smith exterior');
  expect((await runAs(f, owner, { type: 'task.update', id: task, title: 'Prime again', projectId: project, estimatedMinutes: 0, note: '' })).statusCode).toBe(404);
  expect((await runAs(f, owner, { type: 'record.restore', kind: 'task', id: task })).statusCode).toBe(409);
  expect((await runAs(f, owner, { type: 'record.restore', kind: 'project', id: project })).statusCode).toBe(200);
  const restored = await snap(owner);
  expect(restored.tasks.map((t: { id: string }) => t.id).sort()).toEqual([sub, task].sort());
  expect(restored.taskQuestions.map((q: { id: string }) => q.id)).toEqual([question]);
  expect(restored.shoppingItems.map((i: { id: string }) => i.id)).toEqual([request]);
  expect(restored.trash).toEqual([]);
  expect(restored.activity.filter((a: { kind: string }) => a.kind.startsWith('record.')).map((a: { kind: string; body: string; projectId: string }) => [a.kind, a.body, a.projectId]).sort()).toEqual([['record.delete', 'Deleted project “Smith exterior”.', project], ['record.restore', 'Restored project “Smith exterior”.', project]]);
});
it('people delete their own unprocessed items, a running timer blocks deleting a task, and a client with projects stays', async () => {
  const { owner, worker, manager, client, project, task } = await setup();
  const mine = (await runAs(f, worker.headers, { type: 'materialRequest.create', title: 'Gloves', forUserId: worker.id })).json().result.id;
  const theirs = (await runAs(f, manager.headers, { type: 'materialRequest.create', title: 'Rollers', projectId: project })).json().result.id;
  expect((await runAs(f, manager.headers, { type: 'record.delete', kind: 'client', id: client })).statusCode).toBe(409);
  expect((await runAs(f, worker.headers, { type: 'record.delete', kind: 'task', id: task })).statusCode).toBe(403);
  expect((await runAs(f, worker.headers, { type: 'record.delete', kind: 'materialRequest', id: theirs })).statusCode).toBe(403);
  expect((await runAs(f, worker.headers, { type: 'record.delete', kind: 'materialRequest', id: mine })).statusCode).toBe(200);
  expect((await runAs(f, worker.headers, { type: 'record.restore', kind: 'materialRequest', id: mine })).statusCode).toBe(403);
  expect((await runAs(f, owner, { type: 'timeEntry.createManual', taskId: task, date: '2026-09-25', minutes: 30, note: '' })).statusCode).toBe(200);
  expect((await snap(owner)).timeEntries).toHaveLength(1);
  expect((await runAs(f, owner, { type: 'timer.start', taskId: task })).statusCode).toBe(200);
  expect((await runAs(f, manager.headers, { type: 'record.delete', kind: 'task', id: task })).statusCode).toBe(409);
  expect((await runAs(f, owner, { type: 'timer.pause', expectedSessionId: (await snap(owner)).runningTimer.sessionId })).statusCode).toBe(200);
  expect((await runAs(f, manager.headers, { type: 'record.delete', kind: 'task', id: task })).statusCode).toBe(200);
  const view = await snap(manager.headers);
  expect(view.tasks).toHaveLength(0); expect(view.timeEntries).toHaveLength(0); expect(view.projects).toHaveLength(1);
  expect(view.trash.map((e: { kind: string; cascaded: number }) => [e.kind, e.cascaded]).sort()).toEqual([['materialRequest', 0], ['task', 1]]);
  expect((await runAs(f, manager.headers, { type: 'record.restore', kind: 'task', id: task })).statusCode).toBe(200);
  expect((await snap(owner)).timeEntries).toHaveLength(1);
  const expense = (await runAs(f, owner, { type: 'expense.create', purchaseDate: '2026-09-25', description: 'Brushes', category: 'tools', amountCents: 2500, projectId: project })).json().result.id;
  expect((await runAs(f, manager.headers, { type: 'record.delete', kind: 'expense', id: expense })).statusCode).toBe(403);
  expect((await runAs(f, owner, { type: 'record.delete', kind: 'expense', id: expense })).statusCode).toBe(200);
  expect((await snap(owner)).expenses).toHaveLength(0);
  expect((await runAs(f, manager.headers, { type: 'record.restore', kind: 'expense', id: expense })).statusCode).toBe(403);
  expect((await runAs(f, owner, { type: 'record.restore', kind: 'expense', id: expense })).statusCode).toBe(200);
  expect((await snap(owner)).expenses.map((e: { description: string }) => e.description)).toEqual(['Brushes']);
});
