import { describe, expect, it, vi } from 'vitest';
import type { BusinessSnapshot } from '@pirata/contracts/index';
import { createServerStore } from '../../src/state/serverStore';
import { ServiceError, type PirataService } from '../../src/services/api';
const snapshot=(revision=0):BusinessSnapshot=>({schemaVersion:2,timezone:'America/New_York',currency:'USD',revision,serverNow:1000,capabilities:{'clients-projects':'ready','tasks-time':'ready',planning:'ready',spending:'ready',inventory:'ready'},clients:[],projects:[],tasks:[],objectives:[],schedule:[],timeEntries:[],runningTimer:null,expenses:[],materials:[],materialRequirements:[],materialAdjustments:[],equipment:[],maintenance:[],leads:[]});
const result={requestId:'00000000-0000-4000-a000-000000000001',revision:1,serverNow:1000,changed:true,result:{kind:'test'}};
function mock(){return {session:vi.fn().mockResolvedValue({authenticated:true,csrfToken:'a'.repeat(32),expiresAt:100000}),snapshot:vi.fn().mockResolvedValue(snapshot()),login:vi.fn().mockResolvedValue({authenticated:true,csrfToken:'b'.repeat(32),expiresAt:100000}),logout:vi.fn().mockResolvedValue(undefined),execute:vi.fn().mockResolvedValue(result),exportData:vi.fn().mockResolvedValue(snapshot()),previewImport:vi.fn(),importData:vi.fn(),call:vi.fn()} satisfies PirataService;}
const deferred=<T>()=>{let resolve!:(v:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return {promise,resolve};};
describe('server application store',()=>{
 it('initializes once under StrictMode and starts empty without seeding',async()=>{const api=mock(),store=createServerStore(api,()=>1000);await Promise.all([store.initialize(),store.initialize()]);expect(api.session).toHaveBeenCalledTimes(1);expect(api.snapshot).toHaveBeenCalledTimes(1);expect(store.getSnapshot().data?.tasks).toEqual([]);expect(store.getSnapshot().clockOffset).toBe(0);});
 it('opens a fresh signed-out page without an expired-draft warning',async()=>{const api=mock();api.session.mockResolvedValue({authenticated:false,csrfToken:'c'.repeat(32),expiresAt:100000});const store=createServerStore(api);await store.initialize();expect(store.getSnapshot()).toMatchObject({status:'signed-out',data:null,error:''});expect(api.snapshot).not.toHaveBeenCalled();});
 it('sign-out clears records and ignores a slow earlier snapshot',async()=>{const api=mock(),store=createServerStore(api);await store.initialize();const slow=deferred<BusinessSnapshot>();api.snapshot.mockReturnValueOnce(slow.promise);const loading=store.refresh();await Promise.resolve();await store.logout();slow.resolve(snapshot(2));await loading;expect(store.getSnapshot().data).toBeNull();expect(store.getSnapshot().status).toBe('signed-out');});
 it('does not publish optimistic data or silently fall back after failed saves',async()=>{const api=mock(),store=createServerStore(api);await store.initialize();const before=store.getSnapshot().data;api.execute.mockRejectedValue(new ServiceError(503,{code:'STORAGE_UNAVAILABLE',message:'Save failed'}));await expect(store.service.execute({requestId:result.requestId,baseRevision:0,command:{type:'timer.start',taskId:'t'}})).rejects.toThrow('Save failed');expect(store.getSnapshot().data).toBe(before);expect(store.getSnapshot().error).toBe('Save failed');});
 it('rejects stale refresh after an acknowledged newer mutation',async()=>{const api=mock(),store=createServerStore(api);await store.initialize();await store.service.execute({requestId:result.requestId,baseRevision:0,command:{type:'timer.start',taskId:'t'}});await expect(store.refresh()).rejects.toThrow(/latest saved revision/);expect(store.getSnapshot().data?.revision).toBe(0);api.snapshot.mockResolvedValue(snapshot(1));await store.refresh();expect(store.getSnapshot().data?.revision).toBe(1);});
 it('retains loaded records on session expiry so forms can retain drafts, and clears them only after logout',async()=>{const api=mock(),store=createServerStore(api);await store.initialize();api.session.mockResolvedValue({authenticated:false,csrfToken:'c'.repeat(32),expiresAt:100000});await expect(store.refresh()).rejects.toThrow();expect(store.getSnapshot().status).toBe('reauth');expect(store.getSnapshot().data).not.toBeNull();await store.logout();expect(store.getSnapshot().data).toBeNull();});
 it('failed logout never falsely claims the server session ended',async()=>{const api=mock(),store=createServerStore(api);await store.initialize();api.logout.mockRejectedValue(new Error('Offline'));await expect(store.logout()).rejects.toThrow();expect(store.getSnapshot().status).toBe('ready');expect(store.getSnapshot().data).not.toBeNull();});
 it('coalesces simultaneous focus refreshes into one in-flight request plus one follow-up, and preserves monotonic revisions',async()=>{const api=mock(),store=createServerStore(api);await store.initialize();api.snapshot.mockResolvedValue(snapshot(5));await Promise.all([store.refresh(),store.refresh()]);expect(api.snapshot).toHaveBeenCalledTimes(3);api.snapshot.mockResolvedValue(snapshot(3));await store.refresh();expect(store.getSnapshot().data?.revision).toBe(5);});
 // P05
 it('runs one follow-up refresh for callers that joined an in-flight refresh, so a post-save refresh never settles on the older response',async()=>{const api=mock(),store=createServerStore(api,()=>1000);await store.initialize();const slow=deferred<BusinessSnapshot>();api.snapshot.mockReturnValueOnce(slow.promise);const first=store.refresh();await Promise.resolve();await Promise.resolve();api.snapshot.mockResolvedValue(snapshot(2));const joined=store.refresh(),third=store.refresh();expect(third).toBe(joined);slow.resolve(snapshot(1));await first;await joined;expect(store.getSnapshot().data?.revision).toBe(2);expect(api.snapshot).toHaveBeenCalledTimes(3);});
 it('retries the snapshot once when it is behind an acknowledged revision',async()=>{const api=mock(),store=createServerStore(api);await store.initialize();await store.service.execute({requestId:result.requestId,baseRevision:0,command:{type:'timer.start',taskId:'t'}});api.snapshot.mockResolvedValueOnce(snapshot(0)).mockResolvedValueOnce(snapshot(1));await store.refresh();expect(store.getSnapshot().data?.revision).toBe(1);expect(api.snapshot).toHaveBeenCalledTimes(3);});
 it('refreshNow reports offline without a request, failed on an error, and ok otherwise',async()=>{const api=mock(),store=createServerStore(api);await store.initialize();vi.stubGlobal('navigator',{onLine:false});try{expect(await store.refreshNow()).toBe('offline');expect(api.snapshot).toHaveBeenCalledTimes(1);}finally{vi.unstubAllGlobals();}api.snapshot.mockRejectedValueOnce(new ServiceError(503,{code:'STORAGE_UNAVAILABLE',message:'down'}));expect(await store.refreshNow()).toBe('failed');api.snapshot.mockResolvedValue(snapshot(3));expect(await store.refreshNow()).toBe('ok');expect(store.getSnapshot().data?.revision).toBe(3);});
});
