import type { Strings } from '../../i18n';
export const strings:Strings={
  en:{
    'work.previousDay':'Previous day','work.nextDay':'Next day','work.today':'Today','work.date':'Day','work.scope':'Whose list','work.people':'People','work.pools':'Project pools',
    'work.plan':'Plan this day','work.planTitle':'Plan {date}','work.steps':'{done} of {total} steps done','work.onSite':'On site: {names}','work.nobodyPlanned':'Nobody planned on this project yet',
    'work.empty':'Nothing planned for this day.','work.emptyHint':'Pick the tasks and their order. Workers see exactly this list.',
    'work.bring':'Bring','work.requestMaterial':'Request','work.hours.team':'Who worked','work.hours.mine':'Your hours','work.hours.open':'Open hours','work.hours.none':'No hours recorded for this day.','work.hours.note':'Task timers are not paid hours and are not included.','work.hours.total':'{hours} h','work.hours.days':'{days} d ({hours} h)','work.hours.approved':'{count} approved','work.hours.submitted':'{count} submitted','work.openTask':'Open task','work.ask':'Ask the team','work.setTime':'Set time','work.groupMode':'Group by','work.group.time':'By time','work.group.project':'By project','work.group.unscheduled':'Unscheduled','work.plan.timesHint':'Times come from the schedule; reordering only changes the order inside a time.','work.take':'Take this','work.release':'Put back in pool','work.done':'Done','work.open':'Open','work.blocked':'Blocked','work.unassigned':'Unassigned',
    'work.doneBy':'Done by {name} · {time}','work.locked':'Completed. Only an owner can change it now.','work.undoConfirm':'Reopen “{title}”?','work.completeConfirm':'Complete “{title}” and every step under it?',
    'work.paint':'Paint for this project','work.details':'Details','work.hide':'Hide details',
    'work.projects':'Projects','work.allProjects':'All projects','work.allTasks':'All tasks','work.pool':'Project pool','work.mine':'Me',
    'work.plan.project':'Project','work.plan.browse':'Tasks in this project','work.plan.add':'Add','work.plan.added':'Added','work.plan.chosen':'The day’s list, in order','work.plan.nothing':'Nothing chosen yet.','work.plan.up':'Move up','work.plan.down':'Move down','work.plan.remove':'Remove',
    'work.plan.copy':'Copy another day’s list','work.plan.copyButton':'Copy','work.plan.presence':'Who is on this project that day','work.plan.save':'Save plan','work.plan.cancel':'Cancel','work.plan.saved':'Plan saved.','work.plan.noProjects':'Create a project first.',
    'work.question.title':'Question for the team','work.question.recipient':'Goes to the office and everyone on {project}. Morgan AI is not involved.','work.question.task':'Which step?','work.question.body':'Your question','work.question.hint':'Everyone on the project sees it; the office answers. It also shows on the daily report.','work.question.required':'Type the question.','work.question.saved':'Question posted.',
    'work.progress.title':'Team progress','work.progress.none':'No day list for this person.',
  },
  es:{
    'work.previousDay':'Día anterior','work.nextDay':'Día siguiente','work.today':'Hoy','work.date':'Día','work.scope':'Lista de','work.people':'Personas','work.pools':'Pendientes por proyecto',
    'work.plan':'Planear este día','work.planTitle':'Planear {date}','work.steps':'{done} de {total} pasos hechos','work.onSite':'En la obra: {names}','work.nobodyPlanned':'Aún nadie planeado en este proyecto',
    'work.empty':'No hay nada planeado para este día.','work.emptyHint':'Elige las tareas y su orden. Los trabajadores ven exactamente esta lista.',
    'work.bring':'Llevar','work.requestMaterial':'Pedir','work.hours.team':'Quién trabajó','work.hours.mine':'Tus horas','work.hours.open':'Abrir horas','work.hours.none':'No hay horas registradas para este día.','work.hours.note':'Los temporizadores de tareas no son horas pagadas y no se incluyen.','work.hours.total':'{hours} h','work.hours.days':'{days} d ({hours} h)','work.hours.approved':'{count} aprobadas','work.hours.submitted':'{count} enviadas','work.openTask':'Abrir tarea','work.ask':'Preguntar al equipo','work.setTime':'Fijar hora','work.groupMode':'Agrupar por','work.group.time':'Por hora','work.group.project':'Por proyecto','work.group.unscheduled':'Sin hora','work.plan.timesHint':'Las horas vienen del horario; reordenar solo cambia el orden dentro de una hora.','work.take':'Tomar esta','work.release':'Devolver al proyecto','work.done':'Hecho','work.open':'Abierta','work.blocked':'Bloqueada','work.unassigned':'Sin asignar',
    'work.doneBy':'Hecho por {name} · {time}','work.locked':'Completada. Solo un dueño puede cambiarla ahora.','work.undoConfirm':'¿Reabrir “{title}”?','work.completeConfirm':'¿Completar “{title}” y todos sus pasos?',
    'work.paint':'Pintura de este proyecto','work.details':'Detalles','work.hide':'Ocultar detalles',
    'work.projects':'Proyectos','work.allProjects':'Todos los proyectos','work.allTasks':'Todas las tareas','work.pool':'Pendientes del proyecto','work.mine':'Yo',
    'work.plan.project':'Proyecto','work.plan.browse':'Tareas de este proyecto','work.plan.add':'Agregar','work.plan.added':'Agregada','work.plan.chosen':'La lista del día, en orden','work.plan.nothing':'Aún no hay nada elegido.','work.plan.up':'Subir','work.plan.down':'Bajar','work.plan.remove':'Quitar',
    'work.plan.copy':'Copiar la lista de otro día','work.plan.copyButton':'Copiar','work.plan.presence':'Quién está en este proyecto ese día','work.plan.save':'Guardar plan','work.plan.cancel':'Cancelar','work.plan.saved':'Plan guardado.','work.plan.noProjects':'Primero crea un proyecto.',
    'work.question.title':'Pregunta para el equipo','work.question.recipient':'Llega a la oficina y a todos en {project}. Morgan AI no participa.','work.question.task':'¿Sobre qué paso?','work.question.body':'Tu pregunta','work.question.hint':'Todos en el proyecto la ven; la oficina responde. También aparece en el reporte diario.','work.question.required':'Escribe la pregunta.','work.question.saved':'Pregunta publicada.',
    'work.progress.title':'Avance del equipo','work.progress.none':'Esta persona no tiene lista para este día.',
  },
};
