import type { Strings } from '../../i18n';
export const strings:Strings={
  en:{
    'hours.mine':'My hours','hours.team':'Team','hours.week':'Week of {from}','hours.total':'{hours} h','hours.add':'Add hours','hours.none':'No hours this week yet.','hours.status.submitted':'Waiting for approval','hours.status.approved':'Approved','hours.status.rejected':'Rejected','hours.edit':'Edit','hours.remove':'Remove','hours.removeConfirm':'Remove this entry?',
    'hours.dialog.title':'Hours','hours.dialog.person':'Person','hours.dialog.project':'Project','hours.dialog.date':'Date','hours.dialog.kind':'Entry type','hours.dialog.hours':'In / out','hours.dialog.day':'Days','hours.dialog.in':'In','hours.dialog.out':'Out','hours.dialog.break':'Break (minutes)','hours.dialog.days':'How many days','hours.dialog.note':'Note (optional)','hours.dialog.save':'Save','hours.dialog.saved':'Hours saved.','hours.dialog.needProject':'Choose a project.','hours.dialog.needTimes':'Enter in and out times.','hours.dialog.dayHint':'1 day counts as 8 hours in hour totals; pay uses the daily rate.','hours.dialog.needDays':'Choose the days.',
    'hours.pending':'Waiting for approval','hours.approve':'Approve','hours.reject':'Reject','hours.rejectNote':'Reason','hours.rejected':'Rejected: {note}','hours.nonePending':'Nothing waiting for approval.','hours.grid':'Attendance for {date}','hours.gridHint':'Tap a cell to enter hours for that person on that project.','hours.person':'Person','hours.summaryWeek':'This week','hours.summaryMonth':'This month','hours.export':'Export CSV','hours.enterFor':'Enter hours for {name}','hours.noProjects':'No active projects.','hours.byProject':'By project',
  },
  es:{
    'hours.mine':'Mis horas','hours.team':'Equipo','hours.week':'Semana del {from}','hours.total':'{hours} h','hours.add':'Agregar horas','hours.none':'Aún no hay horas esta semana.','hours.status.submitted':'Esperando aprobación','hours.status.approved':'Aprobado','hours.status.rejected':'Rechazado','hours.edit':'Editar','hours.remove':'Quitar','hours.removeConfirm':'¿Quitar esta entrada?',
    'hours.dialog.title':'Horas','hours.dialog.person':'Persona','hours.dialog.project':'Proyecto','hours.dialog.date':'Fecha','hours.dialog.kind':'Tipo de entrada','hours.dialog.hours':'Entrada / salida','hours.dialog.day':'Días','hours.dialog.in':'Entrada','hours.dialog.out':'Salida','hours.dialog.break':'Descanso (minutos)','hours.dialog.days':'Cuántos días','hours.dialog.note':'Nota (opcional)','hours.dialog.save':'Guardar','hours.dialog.saved':'Horas guardadas.','hours.dialog.needProject':'Elige un proyecto.','hours.dialog.needTimes':'Escribe la hora de entrada y salida.','hours.dialog.dayHint':'1 día cuenta como 8 horas en los totales por hora; el pago usa la tarifa diaria.','hours.dialog.needDays':'Elige los días.',
    'hours.pending':'Esperando aprobación','hours.approve':'Aprobar','hours.reject':'Rechazar','hours.rejectNote':'Motivo','hours.rejected':'Rechazado: {note}','hours.nonePending':'Nada pendiente de aprobación.','hours.grid':'Asistencia del {date}','hours.gridHint':'Toca una celda para registrar horas de esa persona en ese proyecto.','hours.person':'Persona','hours.summaryWeek':'Esta semana','hours.summaryMonth':'Este mes','hours.export':'Exportar CSV','hours.enterFor':'Registrar horas de {name}','hours.noProjects':'No hay proyectos activos.','hours.byProject':'Por proyecto',
  },
};
