import { afterEach, describe, expect, it } from 'vitest';
import { randomUUID } from 'node:crypto';
import { createFixture, type Fixture } from './helpers/fixture.js';
import type { PartialHandlers } from '../src/core/context.js';
import { createTaskWithSchedule, closeTimer, setTaskStatus } from '../src/core/shared.js';
import { setOwnerPassword } from '../src/auth/password.js';
import { COOKIE_NAME, SESSION_TTL } from '../src/auth/sessions.js';
import { createApp } from '../src/app.js';
import { notImplemented } from '../src/core/errors.js';
import { openDatabase } from '../src/db/database.js';
import { snapshotSchema } from '@pirata/contracts/index';
import { toLegacyState } from '@pirata/contracts/compatibility';
const fixtures:Fixture[]=[];
async function fixture(options:Parameters<typeof createFixture>[0]={}){const f=await createFixture(options);fixtures.push(f);return f;}
afterEach(async()=>{for(const f of fixtures.splice(0))await f.close();});
// Explicit test handlers exercise real transactions; production feature stubs remain blocked.
const handlers:PartialHandlers={
  'client.create':(ctx,c)=>{const id=ctx.newId();ctx.repo.insert('clients',{id,name:c.name,phone:c.phone,email:c.email,note:c.note,archivedAt:null,createdAt:ctx.serverNow,updatedAt:ctx.serverNow});return {changed:true,result:{kind:'client',id}};},
  'client.update':(ctx,c)=>{ctx.repo.update('clients',c.id,{name:c.name,phone:c.phone,email:c.email,note:c.note,updatedAt:ctx.serverNow});return {changed:true,result:{kind:'client',id:c.id}};},
  'task.create':(ctx,c)=>{const id=ctx.newId();createTaskWithSchedule(ctx,{id,projectId:c.projectId,title:c.title,estimatedMinutes:c.estimatedMinutes,status:'open',note:c.note,createdAt:ctx.serverNow,updatedAt:ctx.serverNow},c.schedule);return {changed:true,result:{kind:'task',id}};},
  'task.setStatus':(ctx,c)=>({changed:setTaskStatus(ctx,c.id,c.status,c.expectedSessionId),result:{kind:'task',id:c.id}}),
  'timer.pause':(ctx,c)=>({changed:closeTimer(ctx,c.expectedSessionId),result:{kind:'timer'}}),
};
const client={type:'client.create' as const,name:'Private test client',phone:'',email:'',note:''};
const task={type:'task.create' as const,projectId:null,title:'Test task',estimatedMinutes:60,note:''};
async function command(f:Fixture,body:unknown,headers?:Record<string,string>){return f.app.inject({method:'POST',url:'/api/v1/commands',headers:headers??await f.authenticate(),payload:body as object});}
describe('authentication and security',()=>{
  it('denies every anonymous business endpoint and never seeds the business snapshot',async()=>{const f=await fixture();for(const url of ['/api/v1/snapshot','/api/v1/export'])expect((await f.app.inject({url})).statusCode).toBe(401);expect((await f.app.inject({method:'POST',url:'/api/v1/commands',payload:f.envelope(client)})).statusCode).toBe(401);const s=await f.app.inject({url:'/api/v1/snapshot',headers:await f.authenticate()});expect(s.headers['cache-control']).toBe('no-store');expect(snapshotSchema.parse(s.json()).clients).toEqual([]);expect(toLegacyState(s.json()).tasks).toEqual([]);});
  it('sets secure cookie flags and rotates session/CSRF at login',async()=>{const f=await fixture();const pre=await f.app.inject({url:'/api/v1/session'});const header=String(pre.headers['set-cookie']);expect(header).toContain('HttpOnly');expect(header).toContain('Secure');expect(header).toContain('SameSite=Strict');expect(header).toContain('Path=/');expect(header).not.toContain('Domain=');const auth=await f.authenticate();expect(auth['x-csrf-token']).not.toBe(pre.json().csrfToken);const s=await f.app.inject({url:'/api/v1/session',headers:auth});expect(s.json().expiresAt).toBeGreaterThan(Date.now()+SESSION_TTL-10000);expect(f.db.prepare('SELECT token_hash FROM sessions').all().every(row=>!auth.cookie.includes((row as {token_hash:string}).token_hash))).toBe(true);});
  it('rejects missing/wrong origin and CSRF on commands, logout and login',async()=>{const f=await fixture();const auth=await f.authenticate();for(const url of ['/api/v1/commands','/api/v1/logout','/api/v1/login'])for(const altered of [{origin:undefined},{origin:'https://evil.test'},{'x-csrf-token':undefined},{'x-csrf-token':'wrong'},{'sec-fetch-site':'cross-site'}]){const headers=Object.fromEntries(Object.entries({...auth,...altered}).filter((entry):entry is [string,string]=>entry[1]!==undefined));expect((await f.app.inject({method:'POST',url,headers,payload:url.endsWith('commands')?f.envelope(client):url.endsWith('login')?{password:f.password}:{}})).statusCode).toBe(403);}});
  it('logout, expiry and recovery revoke sessions; recovery preserves data',async()=>{let now=Date.now();const f=await fixture({now:()=>now,handlers});const auth=await f.authenticate();expect((await command(f,f.envelope(client),auth)).statusCode).toBe(200);expect((await f.app.inject({method:'POST',url:'/api/v1/logout',headers:auth,payload:{}})).statusCode).toBe(204);expect((await f.app.inject({url:'/api/v1/snapshot',headers:auth})).statusCode).toBe(401);const second=await f.authenticate();now+=SESSION_TTL+1;expect((await f.app.inject({url:'/api/v1/snapshot',headers:second})).statusCode).toBe(401);const third=await f.authenticate();await setOwnerPassword(f.db,'different-test-password','recover');expect((await f.app.inject({url:'/api/v1/snapshot',headers:third})).statusCode).toBe(401);expect(f.repo.list('clients')).toHaveLength(1);});
  it('returns generic login failures and enforces persistent rate limits',async()=>{const f=await fixture();const pre=await f.app.inject({url:'/api/v1/session'});const headers={origin:'https://pirata.test','x-csrf-token':pre.json().csrfToken,cookie:COOKIE_NAME+'='+pre.cookies[0].value};for(let i=0;i<10;i++){const response=await f.app.inject({method:'POST',url:'/api/v1/login',headers,payload:{password:'incorrect-test-password'}});expect(response.statusCode).toBe(401);expect(response.json().error.code).toBe('INVALID_CREDENTIALS');}expect((await f.app.inject({method:'POST',url:'/api/v1/login',headers,payload:{password:f.password}})).statusCode).toBe(429);});
  it('never logs credentials, headers or submitted business payloads, even on errors',async()=>{const events:unknown[]=[];const f=await fixture({handlers,audit:e=>events.push(e)});const auth=await f.authenticate();await command(f,f.envelope(client),auth);await command(f,{...f.envelope(client),secret:'private customer text'},auth);const logs=JSON.stringify(events);for(const privateText of [f.password,auth.cookie,client.name,'private customer text','authorization','csrf'])expect(logs).not.toContain(privateText);expect(events.length).toBeGreaterThan(0);});
});
describe('real atomic commands',()=>{
  it('blocked module handlers fail explicitly without increment or receipt',async()=>{const f=await fixture({handlers:{'client.create':notImplemented}});expect((await command(f,f.envelope(client))).statusCode).toBe(501);expect(f.db.prepare('SELECT * FROM command_receipts').all()).toHaveLength(0);});
  it('applies identical retry once after lost response, rejects changed payload and stale revision',async()=>{const f=await fixture({handlers}),auth=await f.authenticate(),body=f.envelope(client);const lost=await command(f,body,auth);expect(lost.statusCode).toBe(200);const replay=await command(f,body,auth);expect(replay.json()).toEqual(lost.json());expect(f.repo.list('clients')).toHaveLength(1);expect((await command(f,{...body,command:{...client,name:'Changed'}},auth)).json().error.code).toBe('IDEMPOTENCY_CONFLICT');expect((await command(f,f.envelope(client),auth)).json().error.currentRevision).toBe(1);expect(f.repo.list('clients')).toHaveLength(1);});
  it('rejects strict unknown fields, invalid dates, dangerous integers and wrong-owner IDs',async()=>{const f=await fixture({handlers}),auth=await f.authenticate();for(const body of [{...f.envelope(client),ownerId:'another'},f.envelope({...client,ownerId:'another'} as typeof client),f.envelope({...task,schedule:{date:'2026-02-30',startMinute:10,endMinute:20,allowOverlap:false}}),f.envelope({type:'expense.create',description:'bad',category:'other',purchaseDate:'2026-09-17',amountCents:Number.MAX_SAFE_INTEGER+1,projectId:null})])expect((await command(f,body,auth)).statusCode).toBe(400);expect((await command(f,f.envelope({type:'client.update',id:'inaccessible-id',name:'X',phone:'',email:'',note:''}),auth)).statusCode).toBe(404);});
  it('rolls back task plus schedule on overlap and response receipt insert failure',async()=>{const f=await fixture({handlers}),auth=await f.authenticate();const b={date:'2026-09-17',startMinute:60,endMinute:120,allowOverlap:false};expect((await command(f,f.envelope({...task,schedule:b}),auth)).statusCode).toBe(200);expect((await command(f,f.envelope({...task,schedule:b},1),auth)).json().error.code).toBe('SCHEDULE_OVERLAP');expect(f.repo.list('tasks')).toHaveLength(1);f.db.exec("CREATE TRIGGER fail_receipt BEFORE INSERT ON command_receipts BEGIN SELECT RAISE(ABORT,'simulated write failure'); END");expect((await command(f,f.envelope(client,1),auth)).statusCode).toBe(409);expect(f.repo.list('clients')).toHaveLength(0);expect((f.db.prepare('SELECT revision FROM data_revisions').get() as {revision:number}).revision).toBe(1);});
  it('storage readonly failure returns unavailable and no success',async()=>{const f=await fixture({handlers}),auth=await f.authenticate();f.db.pragma('query_only=ON');expect((await command(f,f.envelope(client),auth)).statusCode).toBe(503);expect(f.repo.list('clients')).toHaveLength(0);f.db.pragma('query_only=OFF');});
  it('serializes two independent authenticated connections with no lost updates',async()=>{const f=await fixture({handlers});const db2=openDatabase(f.path),app2=createApp({db:db2,origin:'https://pirata.test',handlers});try{const a=await f.authenticate(),b=await f.authenticate();const [one,two]=await Promise.all([command(f,f.envelope(client),a),app2.inject({method:'POST',url:'/api/v1/commands',headers:b,payload:f.envelope({...client,name:'Second'})})]);expect([one.statusCode,two.statusCode].sort()).toEqual([200,409]);expect(f.repo.list('clients')).toHaveLength(1);}finally{await app2.close();db2.close();}});
  it('retains records and idempotent receipts across restart',async()=>{const f=await fixture({handlers}),auth=await f.authenticate(),body=f.envelope(client);const result=await command(f,body,auth);const db2=openDatabase(f.path),app2=createApp({db:db2,origin:'https://pirata.test',handlers});try{expect((await app2.inject({url:'/api/v1/snapshot',headers:auth})).json().clients).toHaveLength(1);expect((await app2.inject({method:'POST',url:'/api/v1/commands',headers:auth,payload:body})).json()).toEqual(result.json());}finally{await app2.close();db2.close();}});
  it('finishes task and closes only the observed timer in one transaction; preserves schedule',async()=>{let now=100000;const f=await fixture({handlers,now:()=>now}),auth=await f.authenticate();const created=await command(f,f.envelope({...task,schedule:{date:'2026-09-17',startMinute:60,endMinute:120,allowOverlap:false}}),auth);const taskId=created.json().result.id;const sessionId=randomUUID();f.repo.insertTimer({sessionId,taskId,startedAt:now});now+=60000;expect((await command(f,f.envelope({type:'task.setStatus',id:taskId,status:'done',expectedSessionId:'older'},1),auth)).statusCode).toBe(409);expect(f.repo.getTimer()?.sessionId).toBe(sessionId);const done=await command(f,f.envelope({type:'task.setStatus',id:taskId,status:'done',expectedSessionId:sessionId},1),auth);expect(done.statusCode).toBe(200);expect(f.repo.getTimer()).toBeNull();expect(f.repo.list('time_entries')[0].id).toBe(sessionId);expect(f.repo.list('schedule_blocks')).toHaveLength(1);});
  it('rejects negative timer duration, omits zero interval, and rolls back failed closure',async()=>{let now=100000;const f=await fixture({handlers,now:()=>now}),auth=await f.authenticate();const created=await command(f,f.envelope(task),auth),taskId=created.json().result.id;let sessionId=randomUUID();f.repo.insertTimer({sessionId,taskId,startedAt:now+1});expect((await command(f,f.envelope({type:'timer.pause',expectedSessionId:sessionId},1),auth)).json().error.code).toBe('CLOCK_CONFLICT');f.repo.correctTimerStart(now);expect((await command(f,f.envelope({type:'timer.pause',expectedSessionId:sessionId},1),auth)).statusCode).toBe(200);expect(f.repo.list('time_entries')).toHaveLength(0);sessionId=randomUUID();f.repo.insertTimer({sessionId,taskId,startedAt:now});now+=1000;f.db.exec("CREATE TRIGGER fail_interval BEFORE INSERT ON time_entries BEGIN SELECT RAISE(ABORT,'failure'); END");expect((await command(f,f.envelope({type:'task.setStatus',id:taskId,status:'blocked',expectedSessionId:sessionId},2),auth)).statusCode).toBe(409);expect(f.repo.getTimer()?.sessionId).toBe(sessionId);expect(f.repo.require('tasks',taskId).status).toBe('open');});
});
