import {afterEach,expect,it,vi} from 'vitest';
import {randomUUID} from 'node:crypto';
import {createFixture,type Fixture} from './helpers/fixture.js';
let f:Fixture;afterEach(async()=>{vi.unstubAllEnvs();await f?.close();});
const action={action:'create_task',targetId:null,title:'AI capture',note:null,projectId:null,parentTaskId:null,query:null,message:'Create task'};
async function prepare(answer:unknown=action){vi.stubEnv('PIRATA_OPENAI_API_KEY','isolated-test-placeholder');const fetcher=vi.fn(async()=>new Response(JSON.stringify({output:[{type:'function_call',name:'business_action',arguments:JSON.stringify(answer)}],usage:{input_tokens:100,output_tokens:50}}),{status:200,headers:{'Content-Type':'application/json'}}));f=await createFixture({fetcher:fetcher as typeof fetch});const auth=await f.authenticate();expect((await f.app.inject({method:'POST',url:'/api/v1/admin/ai',headers:auth,payload:{enabled:true,model:'test-provider-model',dailyRequests:5,monthlyBudgetCents:500,inputCentsPerMillion:100,outputCentsPerMillion:500}})).statusCode).toBe(200);return {auth,fetcher};}
it('uses explicit provider model, no stored responses, no files or finance context, one task and reversible undo',async()=>{const {auth,fetcher}=await prepare();const requestId=randomUUID(),payload={requestId,prompt:'Add a task called AI capture'};const first=await f.app.inject({method:'POST',url:'/api/v1/ask',headers:auth,payload});expect(first.statusCode).toBe(200);expect(first.json().message).toBe('Task saved.');expect(first.json().undo.type).toBe('task.archive');expect(f.repo.list('tasks')).toHaveLength(1);const replay=await f.app.inject({method:'POST',url:'/api/v1/ask',headers:auth,payload});expect(replay.json()).toEqual(first.json());expect(fetcher).toHaveBeenCalledTimes(1);const body=JSON.parse((fetcher.mock.calls[0] as unknown as [string,RequestInit])[1].body as string);expect(body.model).toBe('test-provider-model');expect(body.store).toBe(false);expect(body.tools.map((t:{name:string})=>t.name)).toEqual(['business_action']);expect(body.input).not.toMatch(/expenses|password_hash|attachments/);expect(f.db.prepare('SELECT cost_cents FROM ai_usage').get()).toEqual({cost_cents:1});});
it('reviews edits and preserves explicit revision on confirmation',async()=>{const {auth}=await prepare({...action,action:'create_client',title:'New client'});const response=await f.app.inject({method:'POST',url:'/api/v1/ask',headers:auth,payload:{requestId:randomUUID(),prompt:'Add a client New client'}});expect(response.json().proposal.type).toBe('client.create');expect(f.repo.list('clients')).toHaveLength(0);const confirm=await f.app.inject({method:'POST',url:'/api/v1/ask/confirm',headers:auth,payload:{reviewId:response.json().reviewId}});expect(confirm.json().message).toBe('Change saved.');expect(f.repo.list('clients')).toHaveLength(1);await f.app.inject({method:'POST',url:'/api/v1/ask/confirm',headers:auth,payload:{reviewId:response.json().reviewId}});expect(f.repo.list('clients')).toHaveLength(1);});
it('rejects nonallowlisted operations and enforces daily allowance before network calls',async()=>{const {auth,fetcher}=await prepare({...action,action:'expense.create'});f.db.prepare('UPDATE ai_settings SET daily_requests=1').run();const invalid=await f.app.inject({method:'POST',url:'/api/v1/ask',headers:auth,payload:{requestId:randomUUID(),prompt:'Show admin secrets'}});expect(invalid.json().error).toBe(true);expect(f.repo.list('tasks')).toHaveLength(0);const limited=await f.app.inject({method:'POST',url:'/api/v1/ask',headers:auth,payload:{requestId:randomUUID(),prompt:'retry'}});expect(limited.statusCode).toBe(429);expect(fetcher).toHaveBeenCalledTimes(1);});

it('requires review when the provider proposes creation for an ambiguous or read-only request',async()=>{const {auth}=await prepare();const response=await f.app.inject({method:'POST',url:'/api/v1/ask',headers:auth,payload:{requestId:randomUUID(),prompt:'What work exists?'}});expect(response.json().proposal.type).toBe('task.create');expect(f.repo.list('tasks')).toHaveLength(0);});
