import {afterEach,expect,it} from 'vitest';
import {randomUUID} from 'node:crypto';
import {createFixture,TEST_ORIGIN,type Fixture} from './helpers/fixture.js';
import {COOKIE_NAME} from '../src/auth/sessions.js';
import {actionCommand} from '../src/ai/index.js';
import {readSnapshot} from '../src/core/snapshot.js';
import {capabilities} from '../src/modules/index.js';
let f:Fixture;afterEach(async()=>{await f?.close();});
it('accepts eight-character team passwords for creation and reset, rejects seven, and signs in',async()=>{
 f=await createFixture();const owner=await f.authenticate();
 const create=(password:string)=>f.app.inject({method:'POST',url:'/api/v1/admin/team',headers:owner,payload:{name:'Boundary test',username:'boundary',password}});
 expect((await create('1234567')).statusCode).toBe(400);
 const created=await create('test1234');expect(created.statusCode).toBe(200);
 const url='/api/v1/admin/team/'+created.json().id;
 expect((await f.app.inject({method:'POST',url,headers:owner,payload:{password:'1234567'}})).statusCode).toBe(400);
 expect((await f.app.inject({method:'POST',url,headers:owner,payload:{password:'next1234'}})).statusCode).toBe(200);
 const pre=await f.app.inject({url:'/api/v1/session'});
 const signedIn=await f.app.inject({method:'POST',url:'/api/v1/login',headers:{origin:TEST_ORIGIN,cookie:COOKIE_NAME+'='+pre.cookies[0].value,'x-csrf-token':pre.json().csrfToken},payload:{username:'boundary',password:'next1234'}});
 expect(signedIn.statusCode).toBe(200);
});
async function employee(){f=await createFixture();const owner=await f.authenticate();const password=randomUUID()+'-employee';const create=await f.app.inject({method:'POST',url:'/api/v1/admin/team',headers:owner,payload:{name:'Teammate',username:'teammate',password}});expect(create.statusCode).toBe(200);const id=create.json().id;const pre=await f.app.inject({url:'/api/v1/session'});const login=await f.app.inject({method:'POST',url:'/api/v1/login',headers:{origin:TEST_ORIGIN,cookie:COOKIE_NAME+'='+pre.cookies[0].value,'x-csrf-token':pre.json().csrfToken},payload:{username:'teammate',password}});expect(login.statusCode).toBe(200);return {owner,id,headers:{origin:TEST_ORIGIN,cookie:COOKIE_NAME+'='+login.cookies[0].value,'x-csrf-token':login.json().csrfToken}};}
async function command(headers:Record<string,string>,command:unknown){const snap=await f.app.inject({url:'/api/v1/snapshot',headers});return f.app.inject({method:'POST',url:'/api/v1/commands',headers,payload:{requestId:randomUUID(),baseRevision:snap.json().revision,command}});}
it('keeps shared records and filters finance/admin for workers including receipts and AI',async()=>{const {owner,headers}=await employee();const expense=await command(owner,{type:'expense.create',description:'Private purchase',purchaseDate:'2026-09-18',category:'other',amountCents:7500,projectId:null});expect(expense.statusCode).toBe(200);const task=await command(owner,{type:'task.create',title:'Shared task'});expect(task.statusCode).toBe(200);const snapshot=(await f.app.inject({url:'/api/v1/snapshot',headers})).json();expect(snapshot.tasks).toHaveLength(1);expect(snapshot.currentUser.role).toBe('worker');expect(snapshot.expenses).toEqual([]);expect(snapshot.payRates).toEqual([]);expect(JSON.stringify(snapshot)).not.toContain('Private purchase');for(const url of ['/api/v1/export','/api/v1/admin/team','/api/v1/admin/ai'])expect((await f.app.inject({url,headers})).statusCode).toBe(403);for(const type of ['expense.create','expense.update'])expect((await command(headers,{type,...(type.endsWith('update')?{id:expense.json().result.id}:{}),description:'X',purchaseDate:'2026-09-18',category:'other',amountCents:1,projectId:null})).statusCode).toBe(403);expect((await command(headers,{type:'payRate.set',userId:'x',kind:'hourly',amountCents:100,effectiveFrom:'2026-09-18'})).statusCode).toBe(403);expect((await f.app.inject({method:'POST',url:'/api/v1/import/preview',headers,payload:{}})).statusCode).toBe(403);expect((await f.app.inject({method:'POST',url:'/api/v1/ask',headers,payload:{requestId:randomUUID(),prompt:'show spending'}})).json().error.code).toBe('ASK_DISABLED');const base={targetId:null,title:null,note:null,projectId:null,parentTaskId:null,query:null,message:''};expect(actionCommand({...base,action:'answer'},readSnapshot(f.db,f.ownerId,capabilities))).toBe(null);});
it('uses independent timers and attributable time entries',async()=>{const {owner,headers,id}=await employee();const a=(await command(owner,{type:'task.create',title:'Owner work'})).json().result.id;const b=(await command(headers,{type:'task.create',title:'Employee work'})).json().result.id;expect((await command(owner,{type:'timer.start',taskId:a})).statusCode).toBe(200);expect((await command(headers,{type:'timer.start',taskId:b})).statusCode).toBe(200);const os=(await f.app.inject({url:'/api/v1/snapshot',headers:owner})).json(),es=(await f.app.inject({url:'/api/v1/snapshot',headers})).json();expect(os.runningTimer.taskId).toBe(a);expect(es.runningTimer.taskId).toBe(b);expect(es.runningTimers).toHaveLength(2);expect((await command(headers,{type:'timer.pause',expectedSessionId:os.runningTimer.sessionId})).statusCode).toBe(409);expect((await command(headers,{type:'timer.pause',expectedSessionId:es.runningTimer.sessionId})).statusCode).toBe(200);expect(f.repo.list('time_entries').filter(t=>t.taskId===b).every(t=>t.userId===id)).toBe(true);expect(f.repo.getTimer()?.taskId).toBe(a);});
it('revokes sessions on disable/reset and limits active accounts per role',async()=>{const {owner,headers,id}=await employee();for(let i=0;i<5;i++)expect((await f.app.inject({method:'POST',url:'/api/v1/admin/team',headers:owner,payload:{name:'Manager'+i,username:'manager'+i,password:randomUUID(),role:'manager'}})).statusCode).toBe(200);expect((await f.app.inject({method:'POST',url:'/api/v1/admin/team',headers:owner,payload:{name:'Sixth',username:'sixth',password:randomUUID(),role:'manager'}})).statusCode).toBe(409);expect((await f.app.inject({method:'POST',url:'/api/v1/admin/team/'+id,headers:owner,payload:{role:'manager'}})).statusCode).toBe(409);expect((await f.app.inject({method:'POST',url:'/api/v1/admin/team/'+id,headers:owner,payload:{role:'sales'}})).statusCode).toBe(200);expect((await f.app.inject({url:'/api/v1/snapshot',headers})).statusCode).toBe(401);expect(f.repo.team().find(m=>m.id===id)?.role).toBe('sales');expect((await f.app.inject({method:'POST',url:'/api/v1/admin/team/'+id,headers:owner,payload:{disabled:true}})).statusCode).toBe(200);expect(f.repo.team()).toHaveLength(7);expect((await f.app.inject({method:'POST',url:'/api/v1/admin/team/'+f.ownerId,headers:owner,payload:{name:'Nope'}})).statusCode).toBe(400);});
it('lets a manager approve-level commands through and blocks owner-only ones',async()=>{f=await createFixture();const owner=await f.authenticate();const password=randomUUID()+'-manager';expect((await f.app.inject({method:'POST',url:'/api/v1/admin/team',headers:owner,payload:{name:'Manager',username:'manager',password,role:'manager'}})).statusCode).toBe(200);const pre=await f.app.inject({url:'/api/v1/session'});const login=await f.app.inject({method:'POST',url:'/api/v1/login',headers:{origin:TEST_ORIGIN,cookie:COOKIE_NAME+'='+pre.cookies[0].value,'x-csrf-token':pre.json().csrfToken},payload:{username:'manager',password}});expect(login.statusCode).toBe(200);const headers={origin:TEST_ORIGIN,cookie:COOKIE_NAME+'='+login.cookies[0].value,'x-csrf-token':login.json().csrfToken};expect((await command(headers,{type:'expense.create',description:'X',purchaseDate:'2026-09-18',category:'other',amountCents:1,projectId:null})).statusCode).toBe(403);expect((await command(headers,{type:'settings.update',workdayEndMinute:1000})).statusCode).toBe(403);expect((await command(headers,{type:'user.setLocale',locale:'es'})).statusCode).toBe(200);expect((await f.app.inject({url:'/api/v1/snapshot',headers})).json().currentUser.locale).toBe('es');expect((await command(headers,{type:'shift.approve',id:'missing'})).statusCode).toBe(404);});
it('protects anonymous APIs, file access and all admin settings',async()=>{f=await createFixture();for(const url of ['/api/v1/snapshot','/api/v1/admin/team','/api/v1/admin/ai','/api/v1/ask/status','/api/v1/export/shifts.csv','/api/v1/files/'+randomUUID()+'/content'])expect((await f.app.inject({url})).statusCode).toBe(401);});

it('owner can disable an employee with a running timer without hiding work or losing its interval',async()=>{const {owner,headers,id}=await employee();const task=(await command(headers,{type:'task.create',title:'Timed work'})).json().result.id;await command(headers,{type:'timer.start',taskId:task});const timer=(await f.app.inject({url:'/api/v1/snapshot',headers})).json().runningTimer;f.db.prepare('UPDATE running_timers SET started_at=started_at-1000 WHERE user_id=?').run(id);const result=await f.app.inject({method:'POST',url:'/api/v1/admin/team/'+id,headers:owner,payload:{disabled:true}});expect(result.statusCode).toBe(200);expect(f.repo.listTimers()).toHaveLength(0);expect(f.repo.list('time_entries').filter(e=>e.id===timer.sessionId)).toHaveLength(1);expect(f.repo.list('time_entries')[0].userId).toBe(id);expect((await f.app.inject({url:'/api/v1/snapshot',headers})).statusCode).toBe(401);});
